---
- name: Ensure tmp location exists 
  file:
    path: /tmp/dcos
    state: directory
    mode: 0755
  
- name: Install nano
  yum: >
    name=nano
    state=latest
  
- name: Get Before Date/Time
  shell: date
  register: before_out

- name: Stop Chrony
  shell: systemctl stop chronyd

- name: Sync time manually
  shell: chronyd -q 'server ca.pool.ntp.org iburst'
  ignore_errors: true

- name: Start Chrony
  shell: systemctl start chronyd

- name: Get After Date/Time
  shell: date
  register: after_out

- debug: msg="{{ before_out.stdout_lines }} {{ after_out.stdout_lines }} "
