---
- name: ensure tmp location exists 
  file:
    path: /tmp/dcos
    state: directory
    mode: 0755
    
- name: ensure kubernetes starts with swap tolerance
  lineinfile:
    path: /etc/environment
    regexp: '^%KUBELET_SWAP_ARGS'
    line: 'KUBELET_SWAP_ARGS="–fail-swap-on=false"'
    create: yes

- name: configure chronyd
  include: chronyd.yml

- name: configure sysctl for ip4
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.bridge.bridge-nf-call-iptables =\s'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
  
- name: configure sysctlfor ip6
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.bridge.bridge-nf-call-ip6tables =\s'
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: configure sysctl for ip4
  shell: sysctl net.bridge.bridge-nf-call-iptables=1
  
- name: attempt to reconfigure sysctl net.bridge.bridge-nf-call-iptables
  shell: sysctl -p /etc/sysctl.conf
