---
- name: install net-tools and distro docker
  shell: yum install -y net-tools docker

- name: ensure tmp location exists 
  file:
    path: /tmp/dcos
    state: directory
    mode: 0755
    
- name: ensure kubernetes starts with swap tolerance
  lineinfile:
    path: /etc/environment
    regexp: '^%KUBELET_SWAP_ARGS'
    line: 'KUBELET_SWAP_ARGS="–fail-swap-on=false"'
    create: yes

- name: configure chronyd
  include: chronyd.yml

- name: configure sysctl for ip4
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.bridge.bridge-nf-call-iptables =\s'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
  
- name: configure sysctlfor ip6
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.bridge.bridge-nf-call-ip6tables =\s'
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'

- name: configure sysctl for ip4
  shell: sysctl net.bridge.bridge-nf-call-iptables=1
  
- name: attempt to reconfigure sysctl net.bridge.bridge-nf-call-iptables
  shell: sysctl -p /etc/sysctl.conf

- name: configure dm_raid
  shell: echo 'options dm_raid' > /etc/modprobe.d/dm_raid.conf

- name: configure raid1
  shell: echo 'options raid1' > /etc/modprobe.d/raid1.conf

- name: configure dm_raid and raid1
  shell: modprobe raid1 && modprobe dm_raid
  register: modprobe_out 

- debug: msg="{{ modprobe_out.stdout_lines }}"

- name: restart machines with kernel configurations
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: waiting 30 secs for VMs to come online
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=600
  become: false
