---
- name: ensure tmp location exists 
  file:
    path: /tmp/dcos
    state: directory
    mode: 0755
    
- name: ensure kubernetes starts with swap tolerance
  lineinfile:
    path: /etc/environment
    regexp: '^%KUBELET_SWAP_ARGS'
    line: 'KUBELET_SWAP_ARGS="–fail-swap-on=false"'
    create: yes

- name: configure chronyd
  include: chronyd.yml
