---
# Upgrace CentOS to latest kernel, enable OverlayFS, and disable kdump

- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="Ubuntu base image at {{ kernel_version.stdout }}"

# Upgrade/Update all packages to latest version
- name: update Ubuntu
  shell: "apt-get update"

- name: upgrade Ubuntu
  shell: "apt-get -y upgrade"

- name: find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="Ubuntu kernel as {{ kernel_version.stdout }}"

#- name: restart 
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0

#- name: waiting 30 secs for VM to reboot
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=180
#  become: no

- name: install required packages 
  command: "apt-get -y install chrony curl bash tar nano unzip ipset nfs-common"

- name: make sure the RTC is not local
  command: timedatectl set-local-rtc 0

- name: stop chronyd
  command: systemctl stop chronyd
  ignore_errors: true

- name: force one time clock set
  command: chronyd -q 'pool ca.pool.ntp.org iburst'

- name: start chronyd
  command: systemctl start chronyd

- name: Add elevator=deadline to boot to improve I/O performance on VMware ESXi
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regx }}"
    line: "{{ item.line }}"
    state: present
  become: yes
  with_items:
    - { regx: "GRUB_CMDLINE_LINUX=", line: 'GRUB_CMDLINE_LINUX="quiet splash elevator=deadline"' }
