kind: Service
apiVersion: v1
metadata:
  name: pulsar
  namespace: pulsar
spec:
  selector:
    app: pulsar
  ports:
  - protocol: TCP
    name: pulsar-port1
    port: 6650
    targetPort: 6650
  - protocol: TCP
    name: pulsar-port2
    port: 8080
    targetPort: 8080
  type: LoadBalancer    
