---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pulsar-data-volume-claim
  namespace: pulsar
  annotations:
    volume.beta.kubernetes.io/storage-class: "iscsi-targetd-vg-targetd"  
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
