---
- name: install Docker CE
  yum: >
    name=docker
    state=present

- name: create docker group
  group: >
    name=docker
    state=present

- name: add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
  - docker

- name: ensure /etc/docker exists
  file: 
    path: /etc/docker/ 
    state: directory

- name: start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: verify Docker Configuration
  shell: docker info
  register: docker_out

- debug: msg="{{ docker_out.stdout_lines }}"

- name: set SELinux to permissive mode
  selinux: policy=targeted state=permissive

- name: allow sudo without a tty
  lineinfile: >
    dest=/etc/sudoers
    regexp="^Defaults(\s+)(.*)requiretty(.*)"
    line="#Defaults\1\2requiretty\3"
    backrefs=yes

- name: disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6

- name: enable IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
