
---
- name: set hostname.
  become: yes
  shell: hostnamectl set-hostname {{ inventory_hostname }}

- name: backup hosts file.
  become: yes
  shell: cp /etc/hosts /etc/hosts.orig

- name: create temp hosts file.
  become: yes
  shell: cp /etc/hosts /etc/hosts.gen

- name: add IP address of all hosts to all hosts
  become: yes
  lineinfile:
    dest: /etc/hosts.gen
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups['all'] }}"  

- name: promote hosts file.
  become: yes
  shell: cp /etc/hosts.gen /etc/hosts