---
#- name: Ensure there are no partitions on the 2nd block device dedicated for Docker direct-lvm
#  shell: 
#    cmd: | 
#      fdisk /dev/sdb <<EOF
#      d
#      w
#      EOF

#- name: Restart machines to clear partition table.
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0

#- name: waiting 90 secs for servers to come back
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=90 timeout=180
#  become: false
- name: Configure the docker daemon.json 
  template:
    src: templates/docker_daemon_jsonfile.j2
    dest: /etc/docker/daemon.json

- name: Add the storage configuration into daemon.json
  lineinfile:
    dest: /etc/docker/daemon.json
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^kernel.shmall', line: 'kernel.shmall = 2097152' }
    - { regexp: '^kernel.shmmax', line: 'kernel.shmmax = 134217728' }
    - { regexp: '^fs.file-max', line: 'fs.file-max = 65536' }

- name: 
  blockinfile:
    path: /etc/docker/daemon.json
    insertbefore: "}"
    block: |
      "storage-driver": "devicemapper",
      "storage-opts": [
        "dm.directlvm_device=/dev/sdb",
        "dm.thinp_percent=95",
        "dm.thinp_metapercent=1",
        "dm.thinp_autoextend_threshold=80",
        "dm.thinp_autoextend_percent=20",
        "dm.directlvm_device_force=true"
      ]

- name: Restart the docker daemon with the new storage configuration
  service:
    name: docker
    state: started
    enabled: yes  
      