---
- name: Yum add Docker CE repo
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Yum update packages
  shell: sudo yum makecache fast

- name: Install Docker CE
  yum: >
    name=docker-ce-17.12.0.ce
    state=present

- name: Stop Docker
  service:
    name: docker
    state: stopped


- name: Create docker group
  group: >
    name=docker
    state=present

- name: Add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
  - docker

- name: Ensures /etc/docker exists
  file: 
    path: /etc/docker/ 
    state: directory

- name: Configure the docker daemon.json 
  template:
    src: templates/docker-daemon-dcos-default.j2
    dest: /etc/docker/daemon.json

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Set SELinux to permissive mode
  selinux: policy=targeted state=permissive

- name: Allow sudo without a tty
  lineinfile: >
    dest=/etc/sudoers
    regexp="^Defaults(\s+)(.*)requiretty(.*)"
    line="#Defaults\1\2requiretty\3"
    backrefs=yes

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6

- name: Disable IPv6 loopback alias
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    state: absent

- name: Enable IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
