---
- name: install Docker
  include: docker.yml

- name: install DC/OS Dependencies
  include: dcos-deps.yml

- name: setup dm_raid kernel module
  template:
    src: ../../templates/dcos-centos-dracut.j2
    dest: /etc/dracut.conf

- name: configure dm_raid
  shell: echo 'dm_raid' > /etc/modules-load.d/dm_raid.conf

- name: configure raid1
  shell: echo 'raid1' > /etc/modules-load.d/raid1.conf
  