---
- name: Install direct-lvm dependencies
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: Stop the docker daemon for storage configuration
  service:
    name: docker
    state: stopped

- name: Create the physical volume
  shell: pvcreate /dev/sdb

- name: Create the logical volume
  shell: vgcreate docker /dev/sdb

- name: Create the thinpool volume
  shell: lvcreate --wipesignatures y -n thinpool docker -l 95%VG

- name: Create the thinpoolmeta volume
  shell: lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG

- name: Convert the volumes
  ignore_errors: true
  shell: 
    cmd: |
      lvconvert -y \
        --zero n \
        -c 512K \
        --thinpool docker/thinpool \
        --poolmetadata docker/thinpoolmeta

- name: Create the thinpoolmeta volume
  shell: lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG

- name: Configure the thinpool profile
  template:
    src: templates/docker-thinpool.j2
    dest: /etc/lvm/profile/docker-thinpool.profile

- name: Apply the thinpool profile change
  shell: lvchange --metadataprofile docker-thinpool docker/thinpool
    
- name: Enable LVM volume monitoring
  shell: lvs -o+seg_monitor

- name: Create Docker Backup Folder
  shell: mkdir /var/lib/docker.bk

- name: Move existing docker volume data
  shell: mv /var/lib/docker/* /var/lib/docker.bk

- name: Configure the docker daemon.json 
  template:
    src: templates/docker_daemon_devicemapper_man.j2
    dest: /etc/docker/daemon.json

- name: Restart the docker daemon with the new storage configuration
  service:
    name: docker
    state: restarted
    enabled: yes  

- name: Remove existing docker volume data
  shell: rm -rf /var/lib/docker.bk

- name: waiting for Docker to recover from the LVM changes...
  pause:
    seconds: 60
      
      