---
- name: hide the mail_name from postfix configuration. [MAIL-8818] 
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^#smtpd_banner = $myhostname ESMTP $mail_name'
    line: 'smtpd_banner = $myhostname ESMTP'

- name: hardening SSH configuration [SSH-7408] AllowTcpForwarding (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#AllowTcpForwarding yes'
    line: 'AllowTcpForwarding no'

- name: hardening SSH configuration [SSH-7408] ClientAliveCountMax (3 --> 2)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#ClientAliveCountMax 3'
    line: 'ClientAliveCountMax 2'

- name: hardening SSH configuration [SSH-7408] Compression (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Compression delayed'
    line: 'Compression no'

- name: hardening SSH configuration [SSH-7408] LogLevel (INFO --> VERBOSE)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#LogLevel INFO'
    line: 'LogLevel VERBOSE'

- name: hardening SSH configuration [SSH-7408] MaxAuthTries (6 --> 2)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#MaxAuthTries 6'
    line: 'MaxAuthTries 2'

- name: hardening SSH configuration [SSH-7408] MaxSessions (10 --> 2)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#MaxSessions 10'
    line: 'MaxSessions 2'

- name: hardening SSH configuration [SSH-7408] PermitRootLogin (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin yes'
    line: 'PermitRootLogin no'

- name: hardening SSH configuration [SSH-7408] TCPKeepAlive (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#TCPKeepAlive yes'
    line: 'TCPKeepAlive no'

- name: hardening SSH configuration [SSH-7408] X11Forwarding (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding yes'
    line: 'X11Forwarding no'

- name: hardening SSH configuration [SSH-7408] AllowAgentForwarding (YES --> NO)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#AllowAgentForwarding yes'
    line: 'AllowAgentForwarding no'

- name: audit daemon config [ACCT-9630]  
  template:
    src: templates/auditd-conf.j2
    dest: /etc/audit/auditd.conf

- name: audit daemon rules [ACCT-9630]  
  template:
    src: templates/auditd-rules.j2
    dest: /etc/audit/rules.d/audit.rules

- name: restart machines with hardened profile
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: waiting 180 secs for VMs to come online
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=180 timeout=600
  become: false