---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: confluent-oss-cp-control-center
  namespace: confluent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-control-center
      release: confluent-oss
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "5556"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: cp-control-center
        release: confluent-oss
    spec:
      containers:
      - env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: PLAINTEXT://192.168.1.195:9092
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: http://192.168.1.191:8083
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value: http://192.168.1.193:8083
        - name: CONTROL_CENTER_KSQL_URL
          value: http://192.168.1.194:8088
        - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
          value: http://192.168.1.194:8088
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: http://192.168.1.192:8081
        - name: KAFKA_HEAP_OPTS
          value: -Xms512M -Xmx512M
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "3"
        image: confluentinc/cp-enterprise-control-center:5.2.0
        imagePullPolicy: IfNotPresent
        name: cp-control-center
        ports:
        - containerPort: 9021
          name: cc-http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
