---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-ksql-server-external
  namespace: confluent
spec:
  ports:
  - name: ksql-server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: cp-ksql-server
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.194
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-kafka-connect-external
  namespace: confluent
spec:
  ports:
  - name: kafka-connect
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: cp-kafka-connect
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.193
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-kafka-headless-external
  namespace: confluent
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: cp-kafka
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.195
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-schema-registry-external
  namespace: confluent
spec:
  ports:
  - name: schema-registry
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cp-schema-registry
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.192
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-kafka-rest-external
  namespace: confluent
spec:
  ports:
  - name: rest-proxy
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: cp-kafka-rest
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.196
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-control-center-external
  namespace: confluent
spec:
  ports:
  - name: cc-http
    port: 9021
    protocol: TCP
    targetPort: 9021
  selector:
    app: cp-control-center
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.190
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-zookeeper-headless-external
  namespace: confluent
spec:
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: cp-zookeeper
    release: confluent
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.191
status:
  loadBalancer: {}
