---
- name: set fedora hostname
  include: hostname.yml

- name: configure chronyd
  include: chronyd.yml

- name: update Ubuntu
  apt: 
    name: "*"
    state: latest
  become: true
  register: upgrade_out

- debug: msg="{{ upgrade_out.stdout_lines }}"
