---
- name: set fedora hostname
  include: hostname.yml

- name: configure chronyd
  include: chronyd.yml

- name: ensure gnupg2 is installed
  apt:
      name: "gnupg2"
      state: present
  become : true

- name: update Ubuntu
  apt:
      name: "*"
      state: present
  become : true
 
- name: Add elevator=deadline to boot to improve I/O performance on VMware ESXi
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regx }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regx: "GRUB_CMDLINE_LINUX=", line: 'GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=system/root rd.lvm.lv=system/swap rhgb quiet elevator=noop"' }

- name: restart machines with noop I/O scheduler
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: waiting 30 secs for VMs to come online
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=600
  become: false