
---
- name: Install NTP
  shell: tdnf -y install ntp

- name: Configure the ntp time servers
  template:
    src: templates/ntp-conf.j2
    dest: /etc/ntp.conf
    mode: 0644

- name: Stop NTP
  shell: systemctl stop ntpd

- name: Stop NTP
  shell: ntpdate -u 0.ca.pool.ntp.org

- name: Ensure network time sync is setup
  shell: timedatectl set-ntp true

- name: Enable NTP
  service:
    name: ntpd
    state: started
    enabled: yes  

- name: Verify NTP Sources
  shell: ntpq -p
  register: ntp_out

- debug: msg="{{ ntp_out.stdout_lines }}"

- name: Verify NTP Configurations
  shell: timedatectl
  register: timedate_out

- debug: msg="{{ timedate_out.stdout_lines }}"
