- name: audit daemon config [ACCT-9630]  
  template:
    src: templates/auditd-conf.j2
    dest: /etc/audit/auditd.conf

- name: audit daemon rules [ACCT-9630]  
  template:
    src: templates/auditd-rules.j2
    dest: /etc/audit/rules.d/audit.rules