- name: generate the custom Metrics Server manifest with no TLS verify
  template:
    src: templates/k8s-metrics-server-manifest.j2
    dest: /tmp/metrics-server.yml

- name: apply Metrics Server - Metrics Server Deployment configuration
  shell: kubectl apply -f /tmp/metrics-server.yml
  register: metrics_dep_out

- debug: msg="{{ metrics_dep_out.stdout_lines }}"

- name: wait for the metric server service to initialize
  pause:
    minutes: 1
