- name: generate the NFS client provisioner configuration 
  template:
    src: templates/k8s-nfs-external-client.j2
    dest: /tmp/nfs-external.yml

- name: apply the NFS client provisioner
  shell: kubectl apply -f /tmp/nfs-external.yml
  register: nfs_out

- debug: msg="{{ nfs_out.stdout_lines }}"

- name: waiting for the NFS client provisioner to spin up
  pause:
    seconds: 5

- name: wait for the NFS client provisioner to complete
  shell: "kubectl get pods --all-namespaces | grep -E 'Pending|ContainerCreating|PodInitializing' | wc -l  | xargs"
  register: pending_pods
  until: "pending_pods.stdout == '0'"
  retries: 75
  delay: 10    
