---
- name: Determine base control-builder path
  set_fact:
    cluster_builder_dir: "{{ playbook_dir | replace('/ansible', '') }}"
  when: cluster_pkg_folder is undefined
  run_once: true

- debug: var=cluster_builder_dir
  when: cluster_pkg_folder is undefined
  run_once: true

- name: Determine cluster_pkg_folder
  set_fact:
    cluster_pkg_folder: "{{ inventory_dir | replace(cluster_builder_dir + '/clusters/', '') }}"
  when: cluster_pkg_folder is undefined
  run_once: true

- debug: var=cluster_pkg_folder
  run_once: true

- name: Determine dns settings for docker daemon (override)
  set_fact:
    docker_daemon_dns: '{{ docker_daemon_dns_override }}'
  when: docker_daemon_dns_override is defined 
  run_once: true

- name: Determine dns settings for docker daemon (data network w/ single)
  set_fact:
    docker_daemon_dns: '"{{ data_network_dns }}"'
  when: docker_daemon_dns_override is undefined 
    and data_network_dns is defined
    and data_network_dns2 is undefined
  run_once: true

- name: Determine dns settings for docker daemon (data network w/ 2 entries)
  set_fact:
    docker_daemon_dns: '"{{ data_network_dns }}", "{{ data_network_dns2 }}"'
  when: docker_daemon_dns_override is undefined 
    and data_network_dns is defined
    and data_network_dns2 is defined
  run_once: true

- name: Determine dns settings for docker daemon (main network w/ single)
  set_fact:
    docker_daemon_dns: '"{{ network_dns }}"'
  when: docker_daemon_dns_override is undefined 
    and data_network_dns is undefined
    and network_dns is defined
    and network_dns2 is undefined
  run_once: true

- name: Determine dns settings for docker daemon (main network w/ 2 entries)
  set_fact:
    docker_daemon_dns: '"{{ network_dns }}", "{{ network_dns2 }}"'
  when: docker_daemon_dns_override is undefined 
    and data_network_dns is undefined
    and network_dns is defined
    and network_dns2 is defined
  run_once: true

- name: Calculated dns settings for docker daemon
  debug: var=docker_daemon_dns
  run_once: true

- name: Determine FQDN Node Name
  set_fact:
    node_hostname: "{{ inventory_hostname | replace('.' + network_dn, '') }}"
  run_once: true

- name: Calculated simple node host name
  debug: var=node_hostname
  run_once: true
