- name: Enable Firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes  

- name: Set default Firewalld Zone to DMZ
  shell: firewall-cmd --set-default-zone=dmz

#- name: Enable HTTP Firewalld rule
#  shell: firewall-cmd --zone=dmz --add-service=http --permanent

#- name: Enable HTTPS Firewalld rule
#  shell: firewall-cmd --zone=dmz --add-service=https --permanent

- name: Enable SSH Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=ssh --permanent

- name: Reload the Firewalld rules
  shell: firewall-cmd --reload

- name: List the active Firewalld rules
  shell: firewall-cmd --list-all    
  register: firewalld_rules

- debug: msg="{{ firewalld_rules.stdout_lines }}"

