- name: Stop Firewalld
  service:
    name: firewalld
    state: stopped

- name: Install the Docker Manager Firewall Service definition
  template:
    src: templates/firewalld/swarm-manager-service.j2
    dest: /etc/firewalld/services/swarm-manager.xml
    mode: 644

- name: Install the Docker Worker Firewall Service definition
  template:
    src: templates/firewalld/swarm-worker-service.j2
    dest: /etc/firewalld/services/swarm-worker.xml
    mode: 644

- name: Enable Firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes  

- name: Set default Firewalld Zone to DMZ
  shell: firewall-cmd --set-default-zone=dmz

- name: Enable HTTP Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=http --permanent

- name: Enable HTTPS Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=https --permanent

- name: Enable SSH Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=ssh --permanent

- name: Enable Docker Worker Firewall rules by default
  shell: firewall-cmd --zone=dmz --add-service=swarm-worker --permanent

- name: Reload the Firewalld rules
  shell: firewall-cmd --reload

- name: List the active Firewalld rules
  shell: firewall-cmd --list-all    
  register: firewalld_rules

- debug: msg="{{ firewalld_rules.stdout_lines }}"

