  - name: Ensure the iscs-manifests folder exists in the cluster package
    local_action:
      module: shell
      _raw_params: mkdir -p ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests
    become: false
    when: targetd_server is defined 

  - name: Read VM Node Initiator value for storage class 
    shell: CODE=`cat /etc/iscsi/initiatorname.iscsi` && echo ${CODE//InitiatorName=/}
    register: vm_initiator_code
    when: targetd_server is defined 

  - name: Assign fact 
    set_fact:
      initiator_name: "{{ vm_initiator_code.stdout }}"
    when: targetd_server is defined 

  - name: Generate the iSCSI provisioner, roles and storage class manifest
    local_action:
      module: template
      src: templates/coreos-iscsi-manifests.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/coreos-iscsi.yml
      mode: 0766
    become: false
    when: targetd_server is defined 

  - name: Generate the iSCSI Benchmark manifest
    local_action:
      module: template
      src: templates/coreos-iscsi-bench-pvc-yml.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/coreos-iscsi-bench-pvc.yml
      mode: 0766
    become: false
    run_once: true
    when: targetd_server is defined 

  - name: Generate the iSCSI Benchmark manifest
    local_action:
      module: template
      src: templates/coreos-iscsi-bench-job-yml.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/coreos-iscsi-bench-job.yml
      mode: 0766
    become: false
    run_once: true
    when: targetd_server is defined 

  - name: Generate the iSCSI provisioner secret script
    local_action:
      module: template
      src: templates/coreos-iscsi-secret.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/iscsi-manifests/coreos-iscsi-secret.sh
      mode: 0766
    become: false    
    when: targetd_server is defined 