- name: install targetd service
  yum: >
    name=targetd
    state=latest

- name: install targetd CLI
  yum: >
    name=targetcli
    state=latest

- name: enable the Target.
  service:
    name: target
    state: started
    enabled: yes  

- name: generate custom iSCSI Kublet service def
  template:
    src: templates/targetd-yaml.j2
    dest: /etc/target/targetd.yaml
    mode: 0766

- name: enable the Targetd.
  service:
    name: targetd
    state: started
    enabled: yes  

- name: adjust firewall for iscsi service
  shell: firewall-cmd --add-service=iscsi-target --permanent

- name: adjust firewall for iscsi service
  shell: firewall-cmd --add-port=18700/tcp --permanent 

- name: adjust firewall for iscsi service
  shell: firewall-cmd --reload

- name: create the logical volume
  shell: pvcreate /dev/sdb

- name: create the volume group
  shell: vgcreate vg-targetd /dev/sdb

- name: enable the Targetd.
  service:
    name: targetd
    state: restarted
    enabled: yes  
