---
- name: Adjust max file descriptors
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^fs.file-max', line: 'fs.file-max = 100000' }
    
- name: Adjust hard and soft limits
  template:
    src: templates/limits-conf.j2
    dest: /etc/security/limits.conf
    
- name: Adjust hard and soft limits
  shell: sysctl -p
