---
# Upgrace CentOS to latest kernel, enable OverlayFS, and disable kdump

- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="CentOS base image at {{ kernel_version.stdout }}"

# Upgrade/Update all packages to latest version
- name: Upgrade CentOS
  yum: >
    name=*
    state=latest

- name: find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="CentOS upgraded to {{ kernel_version.stdout }}"

- name: Install required packages 
  command: "yum -y install curl bash iputils tar xz nano unzip ipset nfs-utils yum-plugin-versionlock open-vm-tools"

- name: Make sure the RTC is not local
  command: timedatectl set-local-rtc 0

- name: stop chronyd
  become: true
  command: systemctl stop chronyd

- name: force one time clock set
  become: true
  command: chronyd -q 'pool ca.pool.ntp.org iburst'

- name: start chronyd
  become: true
  command: systemctl start chronyd

# kdump's default config will not work on machines with less than 2GB memory.
# But machine memory is configurable at runtime.
# So just disable kdump (bonus: frees up active memory).
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-kdump-configuration-cli.html
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Kernel_Crash_Dump_Guide/sect-kdump-config-cli.html
- name: disable kdump
  service:
    name: kdump
    state: stopped
    enabled: no

- name: Add elevator=deadline to boot to improve I/O performance on VMware ESXi
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regx }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regx: "GRUB_CMDLINE_LINUX=", line: 'GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=system/root rd.lvm.lv=system/swap rhgb quiet elevator=deadline"' }
