- name: Enable extras
  shell: sudo yum-config-manager --enable extras

- name: Yum install container-selinux
  shell: sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.33-1.git86f33cd.el7.noarch.rpm

- name: Yum add Docker CE repo
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Yum update packages
  shell: sudo yum makecache fast

- name: Install Docker CE
  yum: >
    name=docker-ce
    state=present

- name: Stop Docker
  service:
    name: docker
    state: stopped

- name: Delete all Docker volumes
  file:
    path: /var/lib/docker
    state: absent

- name: Configure Docker to use OverlayFS (part 1)
  set_fact:
    dockerd_cmd: "docker daemon"
    dockerd_arg: "--storage-driver=overlay"

- name: Configure Docker to use OverlayFS (part 2)
  replace: >
    dest=/usr/lib/systemd/system/docker.service
    regexp="^(ExecStart=(.*){{ dockerd_cmd }}) (?!{{ dockerd_arg }})"
    replace="\1 {{ dockerd_arg }} "

- name: Create docker group
  group: >
    name=docker
    state=present

- name: Add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
  - docker

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Set SELinux to permissive mode
  selinux: policy=targeted state=permissive

- name: Allow sudo without a tty
  lineinfile: >
    dest=/etc/sudoers
    regexp="^Defaults(\s+)(.*)requiretty(.*)"
    line="#Defaults\1\2requiretty\3"
    backrefs=yes

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6

# TODO: may be needed at Vagrant provisioning time if added by vagrant
- name: Disable IPv6 loopback alias
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    state: absent

- name: Enable IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
