---
# Upgrae RHEL to latest kernel, enable OverlayFS, and disable kdump

- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="RHEL base image at {{ kernel_version.stdout }}"

# Upgrade/Update all packages to latest version
- name: Upgrade RHEL
  yum: >
    name=*
    state=latest

- name: install packages required 
  command: "yum -y install curl bash iputils tar xz nano unzip ipset nfs-utils yum-plugin-versionlock open-vm-tools"
 
- name: make sure the RTC is not local
  command: timedatectl set-local-rtc 0

- name: stop chronyd
  become: true
  command: systemctl stop chronyd

- name: force one time clock set
  become: true
  command: chronyd -q 'pool ca.pool.ntp.org iburst'

- name: start chronyd
  become: true
  command: systemctl start chronyd

- name: find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="RHEL upgraded to {{ kernel_version.stdout }}"

#- name: Enable OverlayFS
#  copy: >
#    content=overlay
#    dest=/etc/modules-load.d/overlay.conf

# kdump's default config will not work on machines with less than 2GB memory.
# But machine memory is configurable at runtime.
# So just disable kdump (bonus: frees up active memory).
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-kdump-configuration-cli.html
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Kernel_Crash_Dump_Guide/sect-kdump-config-cli.html
- name: Disable kdump
  service:
    name: kdump
    state: stopped
    enabled: no

#- name: Install Docker CE
#  include: docker.yml

- name: enable extras
  shell: sudo yum-config-manager --enable extras

- name: yum install container-selinux
  shell: sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.33-1.git86f33cd.el7.noarch.rpm

- name: yum add Docker CE repo
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo


