
---
- name: iptables INPUT.
  shell: iptables -P INPUT ACCEPT 

- name: iptables INPUT.
  shell: iptables -P OUTPUT ACCEPT 

- name: iptables INPUT.
  shell: iptables -P FORWARD ACCEPT 

- name: iptables INPUT.
  shell: iptables-save > /etc/systemd/scripts/ip4save

- name: Start iptables
  service:
    name: iptables
    state: restarted

- name: Restart the docker daemon 
  service:
    name: docker
    state: restarted
    enabled: yes  
