
---
- name: iptables input.
  replace:
    path: /etc/systemd/scripts/iptables
    regexp: '^iptables -P INPUT   DROP'
    replace: 'iptables -P INPUT   ACCEPT'

- name: iptables forward.
  replace:
    path: /etc/systemd/scripts/iptables
    regexp: '^iptables -P FORWARD DROP'
    replace: 'iptables -P FORWARD ACCEPT'

- name: iptables output.
  replace:
    path: /etc/systemd/scripts/iptables
    regexp: '^iptables -P OUTPUT  DROP'
    replace: 'iptables -P OUTPUT  ACCEPT'      

- name: restart machines.
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: waiting 60 secs for servers to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=60 timeout=120
  become: false