---
- name: Create a Docker Swarm
  include: swarm-cluster.yml

- name: Secure the Swarm Remote API
  include: swarm-secure-api.yml

- name: Install Portainer
  include: swarm-portainer.yml

- name: Configure the Host DB Folders
  include: hostdb-folders.yml

- name: Install Prometheus, Grafana and node-exporter for all nodes
  include: swarm-metrics.yml

- name: Install ELK
  include: swarm-elk.yml
