---
- name: Configure the docker daemon.json file for metrics
  template:
    src: templates/docker_daemon_gelf.j2
    dest: /etc/docker/daemon.json
  when: "docker_enable_metrics|default(false)|bool == true"

- name: Create prometheus host data volume
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Create and install the prometheus configuration file
  template:
    src: templates/prometheus.j2
    dest: /etc/prometheus/prometheus.yml
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Create prometheus host data volume
  file:
    path: /data/prometheus
    state: directory
    mode: 0755
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Create monitoring network... monitor_network 
  shell: docker network create --driver overlay --subnet 10.0.2.0/24 monitor_network
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"
  run_once: true

- name: Install prometheus 
  shell: 
    cmd: | 
      docker service create --replicas 1 --name monitor-prometheus \
      --network monitor_network \
      --constraint "node.role == manager" \
      --mount type=bind,source=/etc/hosts,destination=/etc/hosts \
      --mount type=bind,source=/etc/prometheus/prometheus.yml,destination=/etc/prometheus/prometheus.yml \
      --mount type=bind,source=/data/prometheus,destination=/prometheus \
      --publish 9090:9090/tcp \
      prom/prometheus
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Install node exporter on all nodes (service mode is global)
  shell: 
    cmd: | 
      docker service create --mode global --name monitor-node-exporter \
      --network monitor_network \
      --mount type=bind,source=/proc,destination=/host/proc,readonly \
      --mount type=bind,source=/sys,destination=/host/sys,readonly \
      --mount type=bind,source=/,destination=/rootfs,readonly \
      --publish 9100:9100/tcp \
      prom/node-exporter \
      --collector.procfs /host/proc \
      --collector.sysfs /host/sys \
      --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"  
  when: "docker_enable_metrics|default(false)|bool == true"
  run_once: true

- name: Install cadvisor on all nodes (service mode is global)
  shell: 
    cmd: | 
      docker service create --mode global --name monitor-cadvisor \
      --network monitor_network \
      --mount type=bind,source=/proc,destination=/host/proc,readonly \
      --mount type=bind,source=/sys,destination=/host/sys,readonly \
      --mount type=bind,source=/,destination=/rootfs,readonly \
      --mount type=bind,source=/var/run,destination=/var/run,readonly \
      --mount type=bind,source=/var/lib/docker,destination=/var/lib/docker,readonly \
      --mount type=bind,source=/dev/disk,destination=/dev/disk,readonly \
      --publish 9101:8080/tcp \
      google/cadvisor:latest 
  when: "docker_enable_metrics|default(false)|bool == true"
  run_once: true

- name: Create grafana host data volume
  file:
    path: /data/grafana
    state: directory
    mode: 0755
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Install grafana 
  shell: 
    cmd: | 
      docker service create --replicas 1 --name monitor-grafana \
      --network monitor_network \
      --constraint "node.role == manager" \
      --mount type=bind,source=/etc/hosts,destination=/etc/hosts \
      --mount type=bind,source=/data/grafana,destination=/var/lib/grafana \
      --publish 3000:3000/tcp \
      -e GF_SECURITY_ADMIN_PASSWORD=pass \
      grafana/grafana:latest
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Restart the docker daemons with monitoring configuration
  service:
    name: docker
    state: restarted
    enabled: yes  
  when: "docker_enable_metrics|default(false)|bool == true"
