- name: configure the secret encryption configuration file
  template:
    src: templates/k8s-secrets-conf.j2
    dest: /etc/kubernetes/pki/secrets.conf
    mode: 600
  become: true
  when: k8s_version is not search("1.12") 

- name: configure the secret encryption configuration file for legacy 1.12
  template:
    src: templates/k8s-secrets-conf-legacy.j2
    dest: /etc/kubernetes/pki/secrets.conf
    mode: 600
  become: true
  when: k8s_version is search("1.12") 

- name: adjust kubernetes api server configuration for encryption
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: " - --secure-port=6443"
    line: "    - --encryption-provider-config=/etc/kubernetes/pki/secrets.conf"
    state: present
  become: true
  when: k8s_version is not search("1.12") 

- name: adjust kubernetes api server configuration for encryption in legacy 1.12
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: " - --secure-port=6443"
    line: "    - --experimental-encryption-provider-config=/etc/kubernetes/pki/secrets.conf"
    state: present
  become: true
  when: k8s_version is search("1.12")

- name: wait for the api server to restart
  pause:
    seconds: 15

- name: validate the api is live again 
  shell: kubectl get nodes
  become: true
  register: update_api_out

- debug: msg="{{ update_api_out.stdout_lines }}"

- name: encrypt all the secrets 
  shell: kubectl get secrets --all-namespaces -o json | kubectl replace -f -
  become: true
  register: update_secrets_out

- debug: msg="{{ update_secrets_out.stdout_lines }}"
