---
- name: Find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="Fedora base image at {{ kernel_version.stdout }}"

# Upgrade/Update all packages to latest version
- name: Upgrade Fedora
  dnf: >
    name=*
    state=latest

- name: Install packages required 
  dnf: >
    name={{item}}
    state=present
  with_items:
   - curl
   - bash
   - iputils # for ping
   - tar
   - xz
   - nano
   - unzip
   - ipset
   - nfs-utils
   - docker

- name: Make sure the RTC is not local
  command: timedatectl set-local-rtc 0

- name: stop chronyd
  become: true
  command: systemctl stop chronyd

- name: Force one time clock set
  become: true
  command: chronyd -q 'pool ca.pool.ntp.org iburst'

- name: Start chronyd
  become: true
  command: systemctl start chronyd

#- name: Configure bridge iptables for Fedora install for ip4
#  lineinfile:
#    path: "/etc/sysctl.conf"
#    state: present
#    regexp: '^net.bridge.bridge-nf-call-iptables =\s'
#    line: 'net.bridge.bridge-nf-call-iptables = 1'
  
#- name: Configure bridge iptables for Fedora install for ip6
#  lineinfile:
#    path: "/etc/sysctl.conf"
#    state: present
#    regexp: '^net.bridge.bridge-nf-call-ip6tables =\s'
#    line: 'net.bridge.bridge-nf-call-ip6tables = 1'
  
#- name: Attempt to reconfigure sysctl net.bridge.bridge-nf-call-iptables
#  shell: sysctl -p /etc/sysctl.conf
