---
- name: find kernel version
  command: uname -r
  changed_when: false
  register: kernel_version

- debug: msg="Fedora base image at {{ kernel_version.stdout }}"

- name: register docker repo 
  command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"

  # Upgrade/Update all packages to latest version
- name: upgrade Fedora
  dnf: >
    name=*
    state=latest
  ignore_errors: true

- name: install required base packages
  command: "dnf -y install curl bash iputils tar xz nano unzip ipset nfs-utils open-vm-tools dnf-plugins-core"

- name: install docker-ce and friends
  command: "dnf -y install docker-ce docker-ce-cli containerd.io"

- name: enable docker-ce daemon
  command: "systemctl enable --now docker"

- name: show docker info 
  command: "docker info"
  register: docker_info

- debug: msg="{{ docker_info.stdout_lines }}"

- name: make sure the RTC is not local
  command: timedatectl set-local-rtc 0

- name: stop chronyd
  become: true
  command: systemctl stop chronyd

- name: force one time clock set
  become: true
  command: chronyd -q 'pool ca.pool.ntp.org iburst'

- name: start chronyd
  become: true
  command: systemctl start chronyd

