---
- name: Add the storage configuration into daemon.json
  lineinfile:
    dest: /etc/docker/daemon.json
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    insertafter: "{"
  with_items:
    - { regexp: 'metrics-addr', line: '"metrics-addr" : "0.0.0.0:9323",' }
    - { regexp: 'experimental', line: '"experimental" : true,' }

- name: Create and install the prometheus configuration file
  template:
    src: templates/prometheus.j2
    dest: /etc/prometheus/prometheus.yml
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Create prometheus host data volume
  file:
    path: /data/prometheus
    state: directory
    mode: 0755
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Install prometheus 
  shell: 
    cmd: | 
      docker service create --replicas 1 --name monitor-prometheus \
      --limit-cpu 1 \
      --reserve-cpu 0.5 \
      --limit-memory 1073741824 \
      --reserve-memory 512m \
      --constraint "node.role == manager" \
      --mount type=bind,source=/etc/hosts,destination=/etc/hosts \
      --mount type=bind,source=/etc/prometheus/prometheus.yml,destination=/etc/prometheus/prometheus.yml \
      --mount source=prometheus-data,destination=/prometheus \
      --publish 9090:9090/tcp \
      prom/prometheus
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Stop cadvisor on all nodes 
  shell: docker stop cadvisor
  when: "docker_enable_metrics is defined and docker_enable_metrics"
  ignore_errors: true

- name: Remove cadvisor on all nodes 
  shell: docker rm cadvisor
  when: "docker_enable_metrics is defined and docker_enable_metrics"
  ignore_errors: true

- name: Install cadvisor on all nodes 
  shell: 
    cmd: | 
      docker run \
        --privileged=true \
        --restart=always \
        --memory 536870912 \
        --volume=/cgroup:/cgroup:ro \
        --volume=/:/rootfs:ro \
        --volume=/var/run:/var/run:rw \
        --volume=/sys:/sys:ro \
        --volume=/var/lib/docker/:/var/lib/docker:ro \
        --volume=/dev/disk/:/dev/disk:ro \
        --publish=9101:8080 \
        --detach=true \
        --name=cadvisor \
        google/cadvisor:latest    
  when: "docker_enable_metrics"

- name: Create grafana host data volume
  file:
    path: /data/grafana
    state: directory
    mode: 0755
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Install grafana 
  shell: 
    cmd: | 
      docker service create --replicas 1 --name monitor-grafana \
      --limit-cpu 1 \
      --reserve-cpu 0.5 \
      --limit-memory 1073741824 \
      --reserve-memory 536870912 \
      --constraint "node.role == manager" \
      --mount type=bind,source=/etc/hosts,destination=/etc/hosts \
      --mount type=bind,source=/data/grafana,destination=/var/lib/grafana \
      --publish 3000:3000/tcp \
      -e GF_SECURITY_ADMIN_PASSWORD=pass \
      grafana/grafana:latest
  when: "groups['docker_prometheus_server'] is defined and inventory_hostname in groups['docker_prometheus_server']"

- name: Restart the docker daemons with monitoring configuration
  service:
    name: docker
    state: restarted
    enabled: yes  
  when: "docker_enable_metrics is defined and docker_enable_metrics"
