- name: create Helm Service Account
  shell: kubectl create serviceaccount tiller --namespace kube-system
  register: rbac_out

- debug: msg="{{ rbac_out.stdout_lines }}"

- name: copy Helm RBAC manifest
  copy:
    src: "{{ playbook_dir | replace('/ansible', '') }}/xtras/k8s/helm-rbac.yml"
    dest: /root/

- name: install Helm RBAC manifest
  shell: kubectl apply -f /root/helm-rbac.yml
  register: helmrbac_out

- debug: msg="{{ helmrbac_out.stdout_lines }}"

- name: initialize Helm (install Tiller)
  shell: helm init --service-account tiller
  register: init_out

- debug: msg="{{ init_out.stdout_lines }}"
