- name: copy up the manifest for Istio 1.0.4 CRDS
  copy:
    src: ../xtras/istio/1.0.4/istio-crds.yaml
    dest: /tmp/istio-crds.yml
    mode: 0766   
  become: true   

- name: copy up the manifest for Istio 1.0.4 no TLS
  copy:
    src: ../xtras/istio/1.0.4/istio-demo.yaml
    dest: /tmp/istio-demo.yml
    mode: 0766   
  become: true   

- name: copy up the manifest for Istio 1.0.4 no TLS
  copy:
    src: ../xtras/istio/1.0.4/istio-demo-auth.yaml
    dest: /tmp/istio-demo-auth.yml
    mode: 0766   
  become: true   

- name: install Istio lite 1.0.4 CRDs
  shell: kubectl apply -f /tmp/istio-crds.yml
  register: istio_crd_out

- debug: msg="{{ istio_crd_out.stdout_lines }}"

- name: install Istio 1.0.4 (w/ TLS)
  shell: kubectl apply -f /tmp/istio-demo-auth.yml
  register: istio_out
  when: k8s_istio_tls|bool == true 

- debug: msg="{{ istio_out.stdout_lines }}"
  when: k8s_istio_tls|bool == true 

- name: install Istio 1.0.4 (no TLS)
  shell: kubectl apply -f /tmp/istio-demo.yml
  register: istio_out
  when: k8s_istio_tls|bool != true 

- debug: msg="{{ istio_out.stdout_lines }}"
  when: k8s_istio_tls|bool != true 

- name: wait for the Istio 1.0.4 installation to complete
  pause:
    minutes: "{{ k8s_istio_wait_min }}"

- name: install FlexVolume daemonset into istio-system (needed for sidecar injection)
  shell: kubectl -n istio-system apply -f https://raw.githubusercontent.com/projectcalico/pod2daemon/master/nodeagent/nodeagent.yaml
  register: flex_out

- debug: msg="{{ flex_out.stdout_lines }}"
