#- name: download latest Istio
#  shell: "curl -L https://git.io/getLatestIstio | sh -"
#  args:
#    chdir: /tmp

- name: copy customized Istio CRD manifest
  copy:
    src: "{{ playbook_dir | replace('/ansible', '') }}/xtras/k8s/istio-crds.yml"
    dest: /tmp/

#- name: install Istio CRDs
#  shell: kubectl apply -f /tmp/istio*/install/kubernetes/helm/istio/templates/crds.yaml
#  register: istio_crd_out

- name: install Istio CRDs
  shell: kubectl apply -f /tmp/istio-crds.yml
  register: istio_crd_out

- debug: msg="{{ istio_crd_out.stdout_lines }}"

- name: copy customized Istio manifest
  copy:
    src: "{{ playbook_dir | replace('/ansible', '') }}/xtras/k8s/istio-demo-auth.yml"
    dest: /tmp/

- name: install Istio for Calico authentication (no TLS)
  shell: kubectl apply -f /tmp/istio-demo-auth.yml
  register: istio_out

- debug: msg="{{ istio_out.stdout_lines }}"

#- name: clean up Istio download
#  shell: rm -rf istio*
#  args:
#    chdir: /tmp

- name: wait for the enormous Istio installation to complete
  pause:
    minutes: 3

- name: install FlexVolume daemonset into istio-system (needed for sidecar injection)
  shell: kubectl -n istio-system apply -f https://raw.githubusercontent.com/projectcalico/pod2daemon/master/nodeagent/nodeagent.yaml
  register: flex_out

- debug: msg="{{ flex_out.stdout_lines }}"
