

- name: install latest Istio CRDS for Knative
  shell: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio-crds.yaml | kubectl apply -f -"
  register: istio_crds_out
  args:
    chdir: /tmp

- debug: msg="{{ istio_crds_out.stdout_lines }}"

- name: install latest Istio (NodePort) for Knative
  shell: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml | sed 's/LoadBalancer/NodePort/' | kubectl apply -f -"
  register: istio_out
  args:
    chdir: /tmp
  when: k8s_metallb_address_range is undefined

- debug: msg="{{ istio_out.stdout_lines }}"
  when: k8s_metallb_address_range is undefined

- name: install latest Istio (LoadBalancer) for Knative
  shell: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml | kubectl apply -f -"
  register: istio_out
  args:
    chdir: /tmp
  when: k8s_metallb_address_range is defined

- debug: msg="{{ istio_out.stdout_lines }}"
  when: k8s_metallb_address_range is defined

- name: install FlexVolume daemonset into istio-system (needed for sidecar injection)
  shell: kubectl -n istio-system apply -f https://raw.githubusercontent.com/projectcalico/pod2daemon/master/nodeagent/nodeagent.yaml
  register: flex_out

- debug: msg="{{ flex_out.stdout_lines }}"
