- name: download latest Istio
  shell: "curl -L https://git.io/getLatestIstio | sh -"
  args:
    chdir: /tmp

- name: install Istio CRDs
  shell: kubectl apply -f /tmp/istio*/install/kubernetes/helm/istio/templates/crds.yaml
  register: istio_crd_out

- debug: msg="{{ istio_crd_out.stdout_lines }}"

- name: install latest Istio for Calico authentication (no TLS)
  shell: kubectl apply -f /tmp/istio*/install/kubernetes/istio-demo.yml
  register: istio_out

- debug: msg="{{ istio_out.stdout_lines }}"

- name: clean up Istio download
  shell: rm -rf istio*
  args:
    chdir: /tmp

- name: wait for the enormous Istio installation to complete
  pause:
    minutes: 5

- name: install FlexVolume daemonset into istio-system (needed for sidecar injection)
  shell: kubectl -n istio-system apply -f https://raw.githubusercontent.com/projectcalico/pod2daemon/master/nodeagent/nodeagent.yaml
  register: flex_out

- debug: msg="{{ flex_out.stdout_lines }}"
