- name: update K8s repo
  shell: "yum -y update"
  args:
    warn: false
  become: true
  retries: 50
  delay: 10
  register: result
  until: result.rc is defined and result.rc == 0
  
- name: install K8s (CentOS)
  shell: "yum -y install kubectl-{{ k8s_version }} kubeadm-{{ k8s_version }} kubelet-{{ k8s_version }}"
  args:
    warn: false
  register: k8s_install
  when: cluster_type != "fedora-k8s"
  retries: 50
  delay: 10
  until: k8s_install.rc is defined and k8s_install.rc == 0

- debug: msg="{{ k8s_install.stdout_lines }}"
  when: cluster_type != "fedora-k8s"

- name: install K8s (Fedora)
  shell: "dnf -y install kubectl-{{ k8s_version }} kubeadm-{{ k8s_version }} kubelet-{{ k8s_version }}"
  args:
    warn: false
  register: k8s_install
  when: cluster_type == "fedora-k8s"
  retries: 50
  delay: 10
  until: k8s_install.rc is defined and k8s_install.rc == 0
  
- debug: msg="{{ k8s_install.stdout_lines }}"
  when: cluster_type == "fedora-k8s"
  