- name: download latest Knative (NodePort)
  shell: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml | sed 's/LoadBalancer/NodePort/' > knative.yml"
  register: knative_out
  args:
    chdir: /tmp
  when: k8s_metallb_address_range is undefined

- debug: msg="{{ knative_out.stdout_lines }}"
  when: k8s_metallb_address_range is undefined

- name: download latest Knative (LoadBalancer)
  shell: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml > knative.yml"
  register: knative_out
  args:
    chdir: /tmp
  when: k8s_metallb_address_range is defined

- debug: msg="{{ knative_out.stdout_lines }}"
  when: k8s_metallb_address_range is defined

- name: install Knative Lite 
  shell: kubectl apply -f /tmp/knative.yml
  register: knative_out

- debug: msg="{{ knative_out.stdout_lines }}"

- name: wait for Knative installation to complete
  pause:
    minutes: "{{ k8s_knative_wait_min }}"
