- name: download latest Knative (NodePort)
  local_action:
    module: shell
    _raw_params: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml | sed 's/LoadBalancer/NodePort/' > ../clusters/{{ cluster_pkg_folder }}/knative.yml"
  become: false
  run_once: true
  register: knative_out
  when: k8s_metallb_address_range is undefined
  
- debug: msg="{{ knative_out.stdout_lines }}"
  run_once: true
  when: k8s_metallb_address_range is undefined

- name: download latest Knative (LoadBalancer)
  local_action:
    module: shell
    _raw_params: "curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml > ../clusters/{{ cluster_pkg_folder }}/knative.yml"
  become: false
  run_once: true
  register: knative_out
  when: k8s_metallb_address_range is defined

- debug: msg="{{ knative_out.stdout_lines }}"
  run_once: true
  when: k8s_metallb_address_range is defined

- name: install Knative Lite 
  local_action:
    module: shell
    _raw_params: "kubectl --kubeconfig {{ kube_config_file }} apply -f ../clusters/{{ cluster_pkg_folder }}/knative.yml"
  become: false
  run_once: true
  register: knative_out

- debug: msg="{{ knative_out.stdout_lines }}"
  run_once: true

- name: wait for Knative installation to complete
  pause:
    minutes: "{{ k8s_knative_wait_min }}"
