- name: install local Knative Lite 0.2.2
  local_action:
    module: shell
    _raw_params: "kubectl --kubeconfig {{ kube_config_file }} apply -f ../xtras/k8s/knative/knative-lite-0.2.2.yml"
  become: false
  run_once: true
  ignore_errors: true
  register: knative_out

- debug: msg="{{ knative_out.stdout_lines }}"
  run_once: true

- name: wait for Knative installation to complete
  pause:
    minutes: "{{ k8s_knative_wait_min }}"
