- name: apply default k8s settings
  include: defaults.yml
  run_once: true

- name: remove any updated docker-ce if it exists
  yum:
    name: docker-ce
    state: absent
  when: cluster_type != "fedora-k8s"

- name: install base distro docker for CentOS
  yum:
    name: docker
    state: present
  retries: 10
  delay: 10
  register: result
  until: result.rc is defined and result.rc == 0

- name: install base distro docker for Fedora
  shell: "dnf install -y docker"
  when: cluster_type == "fedora-k8s"
  retries: 10
  delay: 10
  register: result
  until: result.rc is defined and result.rc == 0

- name: start docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: disable firewalld 
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: turn swap off
  shell: swapoff -a

- name: remove swap from fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/dev/mapper/system-swap'

- name: install iSCSI utils for CentOS
  yum: > 
    pkg=iscsi-initiator-utils 
    state=present
  when: cluster_type != "fedora-k8s"
  retries: 50
  delay: 5
  register: result
  until: result.rc is defined and result.rc == 0

- name: install iSCSI utils for Fedora
  dnf: > 
    pkg=iscsi-initiator-utils 
    state=present
  when: cluster_type == "fedora-k8s"
  retries: 50
  delay: 5
  register: result
  until: result.rc is defined and result.rc == 0

- name: ensure the iSCSId daemon is running and enabled on the nodes
  shell: systemctl enable iscsid && systemctl start iscsid

- name: configure the Kubernetes Repo
  become: true
  template:
    src: templates/k8s-repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: disable GPG check on repo due to issues with the K8s source repo.
  lineinfile:
    dest: /etc/yum.repos.d/kubernetes.repo
    line: "{{ item.line }}"
    state: present
  with_items:
    - { line: 'repo_gpgcheck=0' }

- name: install Kubernetes on all the nodes
  include: k8s-install.yml

- name: configure the first Kubernetes master
  include: masters-first.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: configure the remaining Kubernetes masters
  include: masters-next.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname != groups['k8s_masters'][0]"

- name: install the CNI
  include: cni.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: install workaround patches for Kubernetes
  include: patch.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: display cluster master node status
  shell: kubectl get nodes
  register: final_nodes_out
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_nodes_out.stdout_lines }}"
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: remove the master taints (1.14+)
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  become: true
  when: "(k8s_workloads_on_master|bool == True) and inventory_hostname == groups['k8s_masters'][0]"
  ignore_errors: true

- name: remove the master taints (pre 1.14)
  shell: kubectl taint nodes --all node.kubernetes.io/unschedulable:NoSchedule-
  become: true
  when: "(k8s_workloads_on_master|bool == True) and inventory_hostname == groups['k8s_masters'][0]"
  ignore_errors: true

- name: remove the master taints (legacy)
  shell:   kubectl taint nodes --all kubeadmNode-
  become: true
  when: "(k8s_workloads_on_master|bool == True) and inventory_hostname == groups['k8s_masters'][0]"
  ignore_errors: true

- name: configure the Kubernetes workers
  include: workers.yml
  when: "'k8s_workers' in group_names"

- name: configure ingress and load balancing 
  include: ingress.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: configure the Kubernetes Dashboard 
  include: kubernetes-dashboard.yml
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"
    
- name: display cluster worker node status
  shell: kubectl get nodes
  register: final_nodes_out
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_nodes_out.stdout_lines }}"
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: configure log rotation
  become: true
  template:
    src: templates/k8s-log-rotation.j2
    dest: /etc/logrotate.d/containers

- name: list cluster nodes
  shell: kubectl get nodes
  register: final_nodes_out
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_nodes_out.stdout_lines }}"
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: list all running pods
  shell: kubectl get pods --all-namespaces
  register: final_pods_out
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_pods_out.stdout_lines }}"
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- name: list all services
  shell: kubectl get svc --all-namespaces
  register: final_svc_out
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"

- debug: msg="{{ final_svc_out.stdout_lines }}"
  when: "'k8s_masters' in group_names
    and inventory_hostname == groups['k8s_masters'][0]"
