- name: update K8s repo
  shell: "yum -y update"
  become: true

- name: install kubernetes on first master (CentOS)
  yum: > 
    pkg={{item}} 
    state=present
  with_items:
    - "kubectl-{{ k8s_version }}"
    - "kubeadm-{{ k8s_version }}"
    - "kubelet-{{ k8s_version }}"
  when: cluster_type != "fedora-k8s"

- name: install kubernetes on first master (Fedora)
  dnf: > 
    pkg={{item}} 
    state=present
  with_items:
    - "kubectl-{{ k8s_version }}"
    - "kubeadm-{{ k8s_version }}"
    - "kubelet-{{ k8s_version }}"
  when: cluster_type == "fedora-k8s"