- name: Install and accept GPG
  shell: yum install -y kubectl

- name: Install Kubernetes
  yum: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubeadm
    - kubelet

- name: Ensure pki folder exists
  shell: mkdir -p /etc/kubernetes/pki/

- name: Copy the PKI certs
  copy:
    dest: /etc/kubernetes/pki/{{ item }}
    src: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/pki/{{ item }}"
    flat: yes     
  become: true   
  with_items:
    - apiserver.crt  
    - apiserver-kubelet-client.crt  
    - ca.crt  
    - front-proxy-ca.crt  
    - front-proxy-client.crt  
    - sa.key
    - apiserver.key  
    - apiserver-kubelet-client.key  
    - ca.key  
    - front-proxy-ca.key  
    - front-proxy-client.key  
    - sa.pub

- name: Copy the kube-adm.yml
  copy:
    dest: /root/kube-adm.yml
    src: ../clusters/{{ cluster_pkg_folder }}/kube-adm.yml
    flat: no     
  become: true   

- name: Start kubelet 
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: Initialize cluster
  shell: "kubeadm init --config kube-adm.yml"
  args:
    chdir: /root
  register: kubeadm_out
  ignore_errors: true
