- name: Ensure pki folder exists
  shell: mkdir -p /etc/kubernetes/pki/

- name: Copy the PKI certs
  copy:
    dest: /etc/kubernetes/pki/{{ item }}
    src: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/pki/{{ item }}"
    mode: 600
  become: true   
  with_items:
    - sa.key
    - apiserver.key  
    - apiserver-kubelet-client.key  
    - ca.key  
    - front-proxy-ca.key  
    - front-proxy-client.key  
    - sa.pub

- name: Copy the PKI certs
  copy:
    dest: /etc/kubernetes/pki/{{ item }}
    src: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/pki/{{ item }}"
    mode: 644
  become: true   
  with_items:
    - apiserver.crt  
    - apiserver-kubelet-client.crt  
    - ca.crt  
    - front-proxy-ca.crt  
    - front-proxy-client.crt  

- name: Copy the kube-adm.yml
  copy:
    dest: /root/kube-adm.yml
    src: ../clusters/{{ cluster_pkg_folder }}/kube-adm.yml
  become: true   

- name: Start kubelet 
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: Initialize cluster
  shell: "kubeadm init --config kube-adm.yml"
  args:
    chdir: /root
  register: kubeadm_out
  ignore_errors: true
