
- name: patch CoreDNS memory limit to deal with bug in 1.12.1
  shell: "kubectl patch deployment -n=kube-system coredns -p '{\"spec\": {\"template\": {\"spec\":{\"containers\":[{\"image\":\"k8s.gcr.io/coredns:1.2.2\", \"name\":\"coredns\",\"resources\":{\"limits\":{\"memory\":\"512Mi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"70Mi\"}}}]}}}}'"
  register: patch_out

- debug: msg="{{ patch_out.stdout_lines }}"

- name: install canal RBAC manifest
  shell: kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/canal/rbac.yaml
  register: rbac_out

- debug: msg="{{ rbac_out.stdout_lines }}"

- name: install canal manifest
  shell: kubectl apply --validate=false -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/canal/canal.yaml
  register: canal_out

- debug: msg="{{ canal_out.stdout_lines }}"

- name: install flannel CNI manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  register: flannel_out

- debug: msg="{{ flannel_out.stdout_lines }}"

- name: Install Grafana manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
  register: graf_out

- debug: msg="{{ graf_out.stdout_lines }}"

- name: Install Heapster RBAC manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml
  register: heap_rbac_out

- debug: msg="{{ heap_rbac_out.stdout_lines }}"

- name: Install Heapster manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml
  register: heap_out

- debug: msg="{{ heap_out.stdout_lines }}"

- name: Install InfluxDB manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
  register: influx_out

- debug: msg="{{ influx_out.stdout_lines }}"

- name: Install Metrics Server - Aggregated Metrics Reader
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/aggregated-metrics-reader.yaml
  register: metric_1_out

- debug: msg="{{ metric_1_out.stdout_lines }}"

- name: Install Metrics Server - Auth Delegator
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-delegator.yaml
  register: metric_2_out

- debug: msg="{{ metric_2_out.stdout_lines }}"

- name: Install Metrics Server - Auth Reader
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-reader.yaml
  register: metric_3_out

- debug: msg="{{ metric_3_out.stdout_lines }}"

- name: Install Metrics Server - Metrics API Service
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-apiservice.yaml
  register: metric_4_out

- debug: msg="{{ metric_4_out.stdout_lines }}"

- name: Install Metrics Server - Metrics Server Deployment
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-server-deployment.yaml
  register: metric_5_out

- debug: msg="{{ metric_5_out.stdout_lines }}"

- name: Install Metrics Server - Metrics Server Service
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-server-service.yaml
  register: metric_6_out

- debug: msg="{{ metric_6_out.stdout_lines }}"

- name: Install Metrics Server - Resource Reader
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/resource-reader.yaml
  register: metric_7_out

- debug: msg="{{ metric_7_out.stdout_lines }}"

- name: wait for the metrics server to initialize
  pause:
    minutes: 1

- name: install kubernetes dashboard manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
  register: dash_out

- debug: msg="{{ dash_out.stdout_lines }}"