- name: Copy the join_cmd
  copy:
    dest: /root/join_cmd
    src: ../clusters/{{ cluster_pkg_folder }}/join_cmd
    mode: 0766   
  become: true   

- name: Install and accept GPG
  shell: yum install -y kubectl
  when: cluster_type != "fedora-k8s"

- name: Install and accept GPG
  shell: dnf install -y kubectl
  when: cluster_type == "fedora-k8s"

- name: Install Kubernetes
  yum: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubelet
    - kubeadm
  when: cluster_type != "fedora-k8s"

- name: Install Kubernetes
  dnf: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubelet
    - kubeadm
  when: cluster_type == "fedora-k8s"

- name: Start kubelet 
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: Join Worker to Cluser
  shell: "/root/join_cmd"
  register: worker_join

- name: Worker Join Result
  debug: msg="{{ worker_join.stdout_lines }}"
