- name: copy the join_cmd
  copy:
    dest: /root/join_cmd
    src: ../clusters/{{ cluster_pkg_folder }}/join_cmd
    mode: 0766   
  become: true   

- name: update K8s repo
  shell: "yum -y update"
  become: true

- name: install kubernetes on worker nodes (CentOS)
  yum: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubectl-1.12.1-0
    - kubeadm-1.12.1-0
    - kubelet-1.12.1-0
  when: cluster_type != "fedora-k8s"

- name: install kubernetes on worker nodes (Fedora)
  dnf: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubectl-1.12.1-0
    - kubeadm-1.12.1-0
    - kubelet-1.12.1-0
  when: cluster_type == "fedora-k8s"

- name: start kubelet on worker nodes
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: join worker to cluster
  shell: "/root/join_cmd"
  register: worker_join

- name: worker join result
  debug: msg="{{ worker_join.stdout_lines }}"
