- name: Copy the join_cmd
  copy:
    dest: /root/join_cmd
    src: ../clusters/{{ cluster_pkg_folder }}/join_cmd
    mode: 0766   
  become: true   

- name: Install Kubernetes on first Master (CentOS)
  yum: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubectl-1.12.0-0
    - kubeadm-1.12.0-0
    - kubelet-1.12.0-0
  when: cluster_type != "fedora-k8s"

- name: Install Kubernetes on first Master (Fedora)
  dnf: > 
    pkg={{item}} 
    state=present
  with_items:
    - kubectl-1.12.0-0
    - kubeadm-1.12.0-0
    - kubelet-1.12.0-0
  when: cluster_type == "fedora-k8s"

- name: Start kubelet on worker nodes
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: Join Worker to Cluster
  shell: "/root/join_cmd"
  register: worker_join

- name: Worker Join Result
  debug: msg="{{ worker_join.stdout_lines }}"
