- name: copy the join_cmd
  copy:
    dest: /root/join_cmd
    src: ../clusters/{{ cluster_pkg_folder }}/join_cmd
    mode: 0766   
  become: true   

- name: start kubelet on worker nodes
  service:
    name: kubelet
    state: started
    enabled: yes
  become: true

- name: join worker to cluster
  shell: "/root/join_cmd"
  register: worker_join
  when: cluster_type == "centos-k8s" or cluster_type == "centos8-k8s"

- name: worker join result
  debug: msg="{{ worker_join.stdout_lines }}"
  when: cluster_type == "centos-k8s" or cluster_type == "centos8-k8s"

- name: join worker to cluster
  shell: "cat /root/join_cmd | tr -d '\n' >> /root/join_cmd_fedora && echo -e ' --ignore-preflight-errors=SystemVerification \n' >> /root/join_cmd_fedora && bash /root/join_cmd_fedora"
  register: worker_join
  when: cluster_type == "fedora-k8s"

- name: worker join result
  debug: msg="{{ worker_join.stdout_lines }}"
  when: cluster_type == "fedora-k8s"
