  - name: enable and start the iSCSId.
    shell: systemctl enable iscsid && systemctl start iscsid

  - name: check whether kubelet.service contains "--volume iscsiadm"
    command: grep "volume iscsiadm" /etc/systemd/system/kubelet.service
    register: checkiscsiadm
    check_mode: no
    ignore_errors: yes
    changed_when: no
    become: true

  - name: add iSCSI configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: 'Environment="RKT_RUN_ARGS='
    with_items:
      - { regx: "  --volume iscsiadm,kind=host", line: '  --volume iscsiadm,kind=host,source=/usr/sbin/iscsiadm --mount volume=iscsiadm,target=/usr/sbin/iscsiadm \' }
    when: checkiscsiadm.rc != 0

  - name: check whether kubelet.service contains "--volume etc-scsi"
    command: grep "volume etc-scsi" /etc/systemd/system/kubelet.service
    register: checketcscsi
    check_mode: no
    ignore_errors: yes
    changed_when: no
    become: true

  - name: add iSCSI configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: '--volume iscsiadm'
    with_items:
      - { regx: "  --volume etc-scsi,kind=host", line: '  --volume etc-scsi,kind=host,source=/etc/iscsi/ --mount volume=etc-scsi,target=/etc/iscsi \' }
    when: checketcscsi.rc != 0

  - name: check whether kubelet.service contains "--volume iscsid,kind=host"
    command: grep "volume iscsid,kind=host" /etc/systemd/system/kubelet.service
    register: checkiscsid
    check_mode: no
    ignore_errors: yes
    changed_when: no
    become: true

  - name: add iSCSI configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: '--volume etc-scsi'
    with_items:
      - { regx: "  --volume iscsid,kind=host", line: '  --volume iscsid,kind=host,source=/usr/sbin/iscsid --mount volume=iscsid,target=/usr/sbin/iscsid \' }
    when: checkiscsid.rc != 0

  - name: check whether kubelet.service contains "--volume mkfsext4"
    command: grep "volume mkfsext4" /etc/systemd/system/kubelet.service
    register: checkmkfsext4
    check_mode: no
    ignore_errors: yes
    changed_when: no
    become: true

  - name: add iSCSI configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: '--volume iscsid'
    with_items:
      - { regx: "  --volume mkfsext4,kind=host", line: '  --volume mkfsext4,kind=host,source=/usr/sbin/mkfs.ext4 --mount volume=mkfsext4,target=/usr/sbin/mkfs.ext4 \' }
    when: checkmkfsext4.rc != 0

  - name: check whether kubelet.service contains "--volume mkfsfat"
    command: grep "volume mkfsfat" /etc/systemd/system/kubelet.service
    register: checkmkfsfat
    check_mode: no
    ignore_errors: yes
    changed_when: no
    become: true

  - name: add iSCSI configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: '--volume mkfsext4'
    with_items:
      - { regx: "  --volume mkfsfat,kind=host", line: '  --volume mkfsfat,kind=host,source=/usr/sbin/mkfs.fat --mount volume=mkfsfat,target=/usr/sbin/mkfs.fat \' }
    when: checkmkfsfat.rc != 0

  - name: reload unit file
    shell: systemctl daemon-reload

  - name: restart the kubelets.
    shell: systemctl restart kubelet
    when: checkmkfsext4.rc != 0 or checkmkfsfat.rc != 0 or checkiscsid.rc != 0 or checkiscsid.rc != 0 or checketcscsi.rc != 0 or checkiscsiadm.rc != 0

  - name: enable and start the RPCBind.
    shell: systemctl enable rpcbind && systemctl start rpcbind