---
- name: Install direct-lvm dependencies
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: Configure the docker daemon.json 
  template:
    src: templates/docker_daemon_devicemapper.j2
    dest: /etc/docker/daemon.json

#- name: 
#  blockinfile:
#    path: /etc/docker/daemon.json
#    insertbefore: "}"
#    block: |
#      
#      "storage-opts": [
#        "dm.directlvm_device=/dev/sdb",
#        "dm.thinp_percent=95",
#        "dm.thinp_metapercent=1",
#        "dm.thinp_autoextend_threshold=80",
#        "dm.thinp_autoextend_percent=20",
#        "dm.directlvm_device_force=true"
#      ]

- name: Restart the docker daemon with the new storage configuration
  service:
    name: docker
    state: restarted
    enabled: yes  
      