---

- name: Install the Docker Manager Firewall Service definition
  template:
    src: templates/firewalld/swarm-manager-service.j2
    dest: /etc/firewalld/services/swarm-manager.xml
    mode: 644
  when: "inventory_hostname in groups['docker_swarm_manager']"

- name: Install the Docker Worker Firewall Service definition
  template:
    src: templates/firewalld/swarm-worker-service.j2
    dest: /etc/firewalld/services/swarm-worker.xml
    mode: 644
  when: "inventory_hostname in groups['docker_swarm_worker']"

- name: waiting 30s for service definitions to finish installing
  pause:
    seconds: 30

- name: Enable Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes  

- name: Set default Firewalld Zone to DMZ
  shell: firewall-cmd --set-default-zone=dmz

- name: Enable HTTP Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=http --permanent

- name: Enable HTTPS Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=https --permanent

- name: Enable SSH Firewalld rule
  shell: firewall-cmd --zone=dmz --add-service=ssh --permanent

- name: Enable Docker Manager Firewall rules
  shell: firewall-cmd --zone=dmz --add-service=swarm-manager --permanent
  when: "inventory_hostname in groups['docker_swarm_manager']"

- name: Enable Docker Worker Firewall rules
  shell: firewall-cmd --zone=dmz --add-service=swarm-worker --permanent
  when: "inventory_hostname in groups['docker_swarm_worker']"

- name: Reload the Firewalld rules
  shell: firewall-cmd --reload

- name: List the active Firewalld rules
  shell: firewall-cmd --list-all    
  register: firewalld_rules

- debug: msg="{{ firewalld_rules.stdout_lines }}"

- name: Restart the docker daemon with the new firewall rules
  service:
    name: docker
    state: started
    enabled: yes

