---
- name: Stop Docker
  service:
    name: docker
    state: stopped

- name: Uninstall Docker CE
  yum: > 
    pkg={{item}} 
    state=absent
  with_items:
    - docker-ce
    - docker-engine
  ignore_errors: true

- name: Configure EE Docker Url
  copy:
    content: "{{ ucp_download_url }}"
    dest: /etc/yum/vars/dockerurl
  
- name: Install EE Dependencies
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2  

- name: Remove Docker CE Repo
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: Download Docker EE GPG Key
  shell: curl -OL "{{ ucp_download_url }}/centos/gpg"
  args: 
    chdir: /tmp

- name: Move Docker EE GPG Key
  shell: mv /tmp/gpg /etc/dockeree_gpg
    
- name: Import Docker EE GPG Key
  shell: rpm --import /etc/dockeree_gpg

- name: Install Docker EE Repo
  shell: yum-config-manager --add-repo "{{ ucp_download_url }}/centos/docker-ee.repo"

- name: Install Docker EE 
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - docker-ee


- name: Ensure the Docker Daemon is started
  service:
    name: docker
    state: started
    enabled: yes  
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Copy the Docker EE License File
  copy:
    src: ../clusters/{{ cluster_pkg_folder }}/docker_subscription.lic
    dest: /etc/dockeree_license.lic
    mode: 777

- name: Start the UCP 
  shell: 
    cmd: | 
      docker container run --rm -i --name ucp \
      -v /var/run/docker.sock:/var/run/docker.sock \
      docker/ucp:2.2.3 install \
      --admin-username {{ ucp_admin_user }} \
      --admin-password {{ ucp_admin_password }} \
      --license `cat /etc/dockeree_license.lic` \
      --host-address {{ ansible_host }} \
      --san {{ inventory_hostname }} \
      --san {{ docker_swarm_mgmt_cn }} \
      --dns {{ network_dns }} \
      --dns-search {{ network_dn }}
  become: true
  register: ucp_start
  when: "inventory_hostname in groups['docker_swarm_manager'][0]"

- debug: msg="{{ ucp_start.stdout_lines }}"
  when: "inventory_hostname in groups['docker_swarm_manager'][0]"

- name: Remove the Docker EE License File
  file:
    path: /etc/dockeree_license.lic
    state: absent

