---
- name: Stop Docker
  service:
    name: docker
    state: stopped

- name: Uninstall Docker CE
  yum: > 
    pkg={{item}} 
    state=absent
  with_items:
    - docker-ce
    - docker-engine
  ignore_errors: true

- name: Configure EE Docker Url
  copy:
    content: "{{ ucp_download_url }}"
    dest: /etc/yum/vars/dockerurl
  
- name: Install EE Dependencies
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2  

- name: Remove Docker CE Repo
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: Download Docker EE GPG Key
  shell: curl -OL "{{ ucp_download_url }}/centos/gpg"
  args: 
    chdir: /tmp

- name: Move Docker EE GPG Key
  shell: mv /tmp/gpg /etc/dockeree_gpg
    
- name: Import Docker EE GPG Key
  shell: rpm --import /etc/dockeree_gpg

- name: Install Docker EE Repo
  shell: yum-config-manager --add-repo "{{ ucp_download_url }}/centos/docker-ee.repo"

- name: Install Docker EE 
  yum: > 
    pkg={{item}} 
    state=installed
  with_items:
    - docker-ee

- name: Configure the UCP docker daemon.json 
  template:
    src: templates/docker_daemon_ucp.j2
    dest: /etc/docker/daemon.json



