
---
- name: download DC/OS config 
  shell: curl -O http://{{ dcos_boot_server }}:{{ dcos_boot_server_port }}/dcos_install.sh
  args:
    chdir: /tmp/dcos

- name: install DC/OS on master node
  become: true
  become_method: sudo
  shell: bash dcos_install.sh master
  failed_when: "'ERROR' in master_output.stdout or 'FAIL' in master_output.stdout"
  register: master_output
  args:
    chdir: /tmp/dcos

- debug: msg="{{ master_output.stdout_lines }}"
- debug: msg="{{ master_output.stderr_lines }}"

- name: waiting for master to settle in...
  pause:
    minutes: 1
