kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-storage-pvc
  labels:
    app: rabbitmq-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "iscsi-targetd-vg-targetd"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
---
