
---
- name: Set hostname.
  become: yes
  shell: hostnamectl set-hostname {{ inventory_hostname }}

- name: Add IP address of all hosts to all hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups['all'] }}"  
