- name: ensure netfilter is loaded
  shell: modprobe br_netfilter

- name: adjust max file descriptors
  sysctl:
    name: fs.file-max
    value: 100000
    state: present
    
- name: adjust hard and soft limits
  template:
    src: templates/limits-conf.j2
    dest: /etc/security/limits.conf
    
- name: configure sysctl for ip4
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: disable ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present

- name: set reverse path filter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward  
    value: 1
    state: present

- name: enable changes
  shell: sysctl -w net.ipv4.route.flush=1

- name: ensure netfilter is loaded
  shell: modprobe br_netfilter

- name: attempt to reconfigure sysctl
  shell: sysctl -p /etc/sysctl.conf

