- name: modprobe
  shell: modprobe br_netfilter

- name: Adjust max file descriptors
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^fs.file-max', line: 'fs.file-max = 100000' }
    
- name: Adjust hard and soft limits
  template:
    src: templates/limits-conf.j2
    dest: /etc/security/limits.conf
    
- name: configure sysctl for ip4
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.bridge.bridge-nf-call-iptables =\s'
    line: 'net.bridge.bridge-nf-call-iptables = 1'      

- name: disable ipv6
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.ipv6.conf.all.disable_ipv6\s'
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'

- name: set reverse path filter
  lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    regexp: '^net.ipv4.conf.all.rp_filter\s'
    line: 'net.ipv4.conf.all.rp_filter=1'
    
- name: enable changes
  shell: sysctl -w net.ipv4.route.flush=1

- name: attempt to reconfigure sysctl
  shell: sysctl -p /etc/sysctl.conf
