---
# This playbook upgrades Centos7

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: centos-dcos
  - role: centos-dcos-ssh
  - role: dcos-node
  - role: debug
  - role: centos-kernel-tweak
