---
# This playbook upgrades Centos7 for DC/OS

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: centos
  - role: centos-ssh
  - role: sysctl
  - role: dcos-node
  