---
# This playbook upgrades Centos7

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: centos
  - role: centos-sysctl
  - role: centos-ssh
  - role: centos-hardening
  - role: centos-firewalld
  - role: centos-kernel-tweak
  