---
# This playbook creates a CoreOS provisioner on CentOS7

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: centos
  - role: centos-ssh
  - role: coreos-centos-provisioner

  