---
# This playbook upgrades RHEL7

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: rhel
  - role: sysctl
  - role: centos-ssh
  - role: centos-hardening
  - role: centos-firewalld
  