---
# This playbook upgrades Ubuntu 18.04

- hosts: all
  gather_facts: no
  become: true
  roles:
  - role: ubuntu
  - role: sysctl
  - role: ubuntu-ssh
  - role: ubuntu-hardening
  - role: ubuntu-firewalld
  