---
- name: Install node-exporter 
  shell: 
    cmd: | 
      docker \
        run  \
          --name node-exporter \
          --privileged=true \
          --restart=always \
          --volume=/proc:/host/proc:ro \
          --volume=/sys:/host/sys:ro \
          --volume=/:/rootfs:ro \
          --volume=/etc/hostname:/etc/host_hostname:ro \
          -e HOST_HOSTNAME=/etc/host_hostname \
          --publish=9100:9100 \
          --detach \
          basi/node-exporter:latest \
          --path.procfs /host/proc \
          --path.sysfs /host/sys \
          --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)" \
          --collector.textfile.directory /etc/node-exporter/  