---
- name: Install VMware Volume Driver Plugin on Swarm Nodes
  shell: docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest

- name: Install VMware vFile Plugin on Swarm Nodes
  shell: docker plugin install --grant-all-permissions --alias vfile vmware/vfile:latest
  
- name: Prepare to configure vFile
  shell: docker plugin disable vfile

- name: Increase dependent SAMBA service timeout
  shell: docker plugin set vfile VFILE_TIMEOUT_IN_SECOND=90

- name: Prepare to configure vFile
  shell: docker plugin enable vfile