---
# This playbook creates a centos7 docker swarm

- hosts: all
  remote_user: admin
  become: true
  any_errors_fatal: true
  vars:
    # Docker swarm network can be define in order to be sure that
    # swarm cluster doesn't overlap with you infrastructure
    # docker_swarm_network: 10.10.8.0/24

    # You can set any interface, that is listened by docker engine.
    # e.g. docker_swarm_interface: "eth1"
    #docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
    #docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    docker_swarm_port: 2377
    docker_tls_port: 2376
    docker_enable_metrics: true
    contiv_remote_user: admin

  roles:
  - role: common
  - role: centos
  - role: centos-swarm-firewall
  - role: swarm
  - role: swarm-secure-api
  - role: portainer
  - role: centos-swarm-monitoring
  - role: nfs-shares
  
  tasks:  
  - name: Generate the wrapper docker-env script
    local_action:
      module: template
      src: templates/docker-env.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/docker-env
      mode: 0766
    when: "inventory_hostname == groups['docker_swarm_manager'][0]"
    become: false

  - name: Generate the client test script
    local_action:
      module: template
      src: templates/test-{{ cluster_type }}.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/test-cluster
      mode: 0766
    when: "inventory_hostname == groups['docker_swarm_manager'][0]"
    become: false

  - name: Remove tmp cluster folder if exists
    local_action:
      module: shell
      _raw_params: "rm -rf ../tmp/{{ cluster_pkg_folder }}"
    become: false
    when: "inventory_hostname == groups['docker_swarm_manager'][0]"
    ignore_errors: true
