---
# This playbook creates a centos dc/os cluster

- hosts: all
  remote_user: admin
  become: true
  gather_facts: false
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: common
  - role: centos
  - role: dcos
  
  
- hosts: dcos_boot
  remote_user: admin
  gather_facts: false
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: dcos_boot
  
- hosts: dcos_masters
  serial: 1
  remote_user: admin
  gather_facts: false
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: dcos_master

  tasks:
  - name: Generate the client test script
    local_action:
      module: template
      src: templates/test-{{ cluster_type }}.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/test-cluster
      mode: 0766
    become: false
    when: "inventory_hostname == groups['dcos_masters'][0]"
  
  - name: Remove tmp cluster folder if exists
    local_action:
      module: shell
      _raw_params: "rm -rf ../tmp/{{ cluster_pkg_folder }}"
    become: false
    when: "inventory_hostname == groups['dcos_masters'][0]"
    ignore_errors: true

- hosts: dcos_agents_private,dcos_agents_public
  remote_user: admin
  become: true
  become_method: sudo
  gather_facts: false
  any_errors_fatal: true
  vars:
  
  roles:
  - role: dcos_agent
    
    