---
# This playbook creates a centos dc/os cluster

- hosts: all
  remote_user: admin
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: centos
  - role: dcos
  
  
- hosts: dcos_boot
  remote_user: admin
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: dcos_boot
  
- hosts: dcos_masters
  serial: 1
  remote_user: admin
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:

  roles:
  - role: dcos_master

- hosts: dcos_agents_private,dcos_agents_public
  remote_user: admin
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars:
  
  roles:
  - role: dcos_agent
    
    