---
# This playbook changes the target_user password on the remote systems

- hosts: all
  remote_user: "{{ remote_user }}"
  become: true
  any_errors_fatal: true
  vars:
  
  tasks:
  - name: Change password for target_user
    user: 
      name: "{{ target_user }}"
      update_password: always 
      password: "{{ target_password_hash }}"

