- hosts: coreos_controllers
  become: true
  any_errors_fatal: true
  gather_facts: false

  roles:
    - common

  tasks:

  - name: Generate vSphere Storage provider configuration
    template:
      src: templates/vsphere-conf.j2
      dest: /etc/kubernetes/vsphere.conf
      mode: 0766

  - name: Generate vSphere Storage provider configuration
    local_action:
      module: template
      src: templates/vsphere-conf.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/vsphere.conf
    run_once: true
    become: false

  - name: Add vSphere configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regx: " --cloud-provider=", line: '--cloud-provider=vsphere --cloud-config=/etc/kubernetes/vsphere.conf \' }

  - name: Extract the kube-apiserver manifest and add cloud provider configuration
    local_action:
      module: shell
      _raw_params: kubectl get ds kube-apiserver -n kube-system -o yaml > ../clusters/{{ cluster_pkg_folder }}/kube-apiserver.yaml
    run_once: true
    become: false

  - name: Copy kube-apiserver manifest for adjustment
    local_action:
      module: shell
      _raw_params: cp ../clusters/{{ cluster_pkg_folder }}/kube-apiserver.yaml ../clusters/{{ cluster_pkg_folder }}/kube-apiserver-vsphere.yaml
    run_once: true
    become: false

  - name: Amend kube-apiserver manifest with --cloud-provider setting
    local_action:
      module: lineinfile
      dest: ../clusters/{{ cluster_pkg_folder }}/kube-apiserver-vsphere.yaml
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      mode: 0766
    become: false
    with_items:
      - { regx: "      - --cloud-provider=", line: "        - --cloud-provider=vsphere" }
    run_once: true

  - name: Amend kube-apiserver manifest with --cloud-provider setting
    local_action:
      module: lineinfile
      dest: ../clusters/{{ cluster_pkg_folder }}/kube-apiserver-vsphere.yaml
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: "      - --cloud-provider="
      mode: 0766
    become: false
    with_items:
      - { regx: "%--cloud-config=", line: "        - --cloud-config=/etc/vsphere" }
    run_once: true
 
  - name: Apply modified kube-apiserver manifest.
    local_action:
      module: shell
      _raw_params: kubectl apply -f ../clusters/{{ cluster_pkg_folder }}/kube-apiserver-vsphere.yaml
    run_once: true
    become: false

  - name: Extract the kube-controller-manager manifest and add cloud provider configuration
    local_action:
      module: shell
      _raw_params: kubectl get deploy kube-controller-manager -n kube-system -o yaml > ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager.yaml
    run_once: true
    become: false

  - name: Copy kube-controller-manager manifest for adjustment
    local_action:
      module: shell
      _raw_params: cp ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager.yaml ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager-vsphere.yaml
    run_once: true
    become: false

  - name: Amend kube-controller-manager manifest with --cloud-provider setting
    local_action:
      module: lineinfile
      dest: ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager-vsphere.yaml
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      mode: 0766
    become: false
    run_once: true
    with_items:
      - { regx: "        - --cloud-provider=", line: "        - --cloud-provider=vsphere" }

  - name: Amend kube-controller-manager manifest with --cloud-provider setting
    local_action:
      module: lineinfile
      dest: ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager-vsphere.yaml
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: "        - --cloud-provider="
      mode: 0766
    become: false
    run_once: true
    with_items:
      - { regx: "%--cloud-config=", line: "        - --cloud-config=/etc/kubernetes/vsphere.conf" }

  - name: Apply modified kube-apiserver manifest.
    local_action:
      module: shell
      _raw_params: kubectl apply -f ../clusters/{{ cluster_pkg_folder }}/kube-controller-manager-vsphere.yaml
    run_once: true
    become: false

  - name: Daemon Reload.
    shell: systemctl daemon-reload

  - name: Restart the Kubelets.
    shell: systemctl restart kubelet

- hosts: coreos_workers
  become: true
  any_errors_fatal: true
  gather_facts: false

  roles:
    - common

  tasks:

  - name: Add vSphere configuration to kubelet.service file
    lineinfile:
      dest: /etc/systemd/system/kubelet.service
      regexp: "{{ item.regx }}"
      line: "{{ item.line }}"
      state: present
      insertafter: 'Environment="RKT_RUN_ARGS='
    with_items:
      - { regx: " --cloud-provider=", line: '--cloud-provider=vsphere' }
    
  - name: Daemon Reload.
    shell: systemctl daemon-reload

  - name: Restart the Kubelets.
    shell: systemctl restart kubelet
      