# This playbook deploys a CoreOS Cluster via PXE/iPXE and Matchbox services
---
- hosts: vmware_vms
  gather_facts: false
  vars:
    gen_script_folder: ../tmp/{{ cluster_pkg_folder }}
    deployment_scale: "{{ deployment_scale | default(50) }}"

  roles:
    - role: common
  
  tasks:  

    - name: Scan the VMS for the VM ID
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/getallvms | grep {{ inventory_hostname }} | cut -d" " -f1
      register: vm_id
    
    - debug: msg="{{ vm_id.stdout }}"

    - name: Find the MAC
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/device.getdevices {{ vm_id.stdout }} | grep macAddress | sed -e 's/         macAddress = "//g' | sed -e 's/", //g'
      register: vm_mac_addr
    
    - debug: msg="{{ vm_mac_addr.stdout_lines }}"

    - name: Stop the VMs
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/power.off {{ vm_id.stdout }} 
      when: vm_id.stdout is defined
      ignore_errors: true

    - name: Adjust the memSize value on the ESXi VM
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "sed '/memSize/s/.*/memSize\ =\ \"{{ memsize }}\"/' /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx > /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted"
      when: memsize is defined

    - name: Copy the adjusted vmx into place
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "cp /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx"
      when: numvcpus is defined

    - name: Adjust the numvcpus value on the ESXi VM
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "sed '/numvcpus/s/.*/numvcpus\ =\ \"{{ numvcpus }}\"/' /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx > /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted"
      when: numvcpus is defined

    - name: Copy the adjusted vmx into place
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "cp /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx"
      when: numvcpus is defined

    - name: Adjust the Primary interface network name
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "sed '/ethernet0.networkName/s/.*/ethernet0.networkName\ =\ \"{{ esxi_net }}\"/' /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx > /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted"
      when: esxi_net is defined

    - name: Copy the adjusted vmx into place
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "cp /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx"
      when: esxi_net is defined

    - name: Delete the adjusted vmx file
      local_action:
        module: shell
        _raw_params: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ esxi_user }}@{{ esxi_host }} "rm /vmfs/volumes/{{ esxi_ds }}/{{ inventory_hostname }}/{{ inventory_hostname }}.vmx-adjusted"
      ignore_errors: true


- hosts: coreos_controllers,coreos_workers
  remote_user: admin
  become: true
  any_errors_fatal: true
  gather_facts: false
  vars:

    tectonic_controller_domain: "{{ tectonic_controller_dn }}"

    tectonic_matchbox_http_url: "http://{{ provisioner_server_dn }}:8080"
    tectonic_matchbox_rpc_endpoint: "{{ provisioner_server_dn }}:8081"

    tectonic_ingress_domain: "{{ tectonic_ingress_dn }}"

    tectonic_service_cidr: "10.3.0.0/16"

    tectonic_container_linux_channel: "stable"
    tectonic_container_linux_version: "latest"

  tasks:

  - name: Load tectonic_matchbox_ca
    local_action:
      module: shell
      _raw_params: "cat ../clusters/{{ cluster_pkg_folder }}/matchbox-certs/ca.crt"
    register: tectonic_matchbox_ca_load
    become: false
    run_once: true

  - debug: msg="{{ tectonic_matchbox_ca_load.stdout }}" 
    run_once: true

  - name: Set tectonic_matchbox_ca
    set_fact:
      tectonic_matchbox_ca: "{{ tectonic_matchbox_ca_load.stdout }}"
    run_once: true

  - name: Load tectonic_matchbox_client_cert
    local_action:
      module: shell
      _raw_params: "cat ../clusters/{{ cluster_pkg_folder }}/matchbox-certs/client.crt"
    register: tectonic_matchbox_client_cert_load
    become: false
    run_once: true

  - debug: msg="{{ tectonic_matchbox_client_cert_load.stdout }}" 
    run_once: true

  - name: Set tectonic_matchbox_client_cert
    set_fact:
      tectonic_matchbox_client_cert: "{{ tectonic_matchbox_client_cert_load.stdout }}"
    run_once: true

  - name: Load tectonic_matchbox_client_key
    local_action:
      module: shell
      _raw_params: "cat ../clusters/{{ cluster_pkg_folder }}/matchbox-certs/client.key"
    register: tectonic_matchbox_client_key_load
    become: false
    run_once: true

  - debug: msg="{{ tectonic_matchbox_client_key_load.stdout }}" 
    run_once: true

  - name: Set tectonic_matchbox_client_key
    set_fact:
      tectonic_matchbox_client_key: "{{ tectonic_matchbox_client_key_load.stdout }}"
    run_once: true

  - name: Load ssh key
    local_action:
      module: shell
      _raw_params: "cat ../node-packer/keys/authorized_keys"
    register: tectonic_ssh_key_load
    become: false
    run_once: true

  - debug: msg="{{  tectonic_ssh_key_load.stdout }}" 
    run_once: true

  - name: Set tectonic_ssh_authorized_key
    set_fact:
      tectonic_ssh_authorized_key: "{{  tectonic_ssh_key_load.stdout }}"
    run_once: true

  - name: Generate the terraform.vars file
    local_action:
      module: template
      src: templates/coreos-terraform-alt.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/terraform.tfvars
      mode: 0766
    become: false
    run_once: true

  - name: Generate the controllers.csv file
    local_action:
      module: template
      src: templates/coreos-controllers-csv.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/manual-controllers.csv
      mode: 0766
    become: false
    run_once: true

  - name: Generate the workers.csv file
    local_action:
      module: template
      src: templates/coreos-workers-csv.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/manual-workers.csv
      mode: 0766
    become: false
    run_once: true

- hosts: coreos_provisioner,coreos_workers,coreos_controllers
  remote_user: admin
  become: true
  any_errors_fatal: true
  gather_facts: false
  vars:

  tasks:

  - name: Process the DHCP template file
    local_action:
      module: template
      src: templates/coreos-dhcpd-static-block.j2
      dest: ../tmp/coreos-dhcpd-block.txt
    become: false
    when: inventory_hostname in groups['coreos_provisioner']
    run_once: true

  - name: Load dhcpd block
    local_action:
      module: shell
      _raw_params: "cat ../tmp/coreos-dhcpd-block.txt"
    register: coreos_dhcpd_static_block
    become: false
    run_once: true

  - debug: msg="{{ coreos_dhcpd_static_block.stdout_lines }}" 
    run_once: true

  - name: Stop the DHCPD server
    service:
      name: dhcpd
      state: stopped
    when: inventory_hostname in groups['coreos_provisioner']

  - name: Remove the DHCP server with the static blocks
    blockinfile:
      dest: /etc/dhcp/dhcpd.conf
      state: absent
      marker: "# {mark} {{ cluster_name }} CLUSTER MANAGED BLOCK"
      block: |
        {{ coreos_dhcpd_static_block.stdout }}
    when: inventory_hostname in groups['coreos_provisioner']

  - name: Update the DHCP server with the static blocks
    blockinfile:
      dest: /etc/dhcp/dhcpd.conf
      insertafter: "EOF"
      marker: "# {mark} {{ cluster_name }} CLUSTER MANAGED BLOCK"
      block: |
        {{ coreos_dhcpd_static_block.stdout }}
    when: inventory_hostname in groups['coreos_provisioner']

  - name: Start the DHCPD server
    service:
      name: dhcpd
      state: started
    when: inventory_hostname in groups['coreos_provisioner']
        
  - name: Clean up tmp dhcpd block
    local_action:
      module: shell
      _raw_params: "rm ../tmp/coreos-dhcpd-block.txt"
    become: false
    run_once: true
        