- hosts: coreos_controllers,coreos_workers
  become: true
  any_errors_fatal: true
  gather_facts: false
  vars:

    tectonic_controller_domain: "{{ tectonic_controller_dn }}"
    tectonic_matchbox_http_url: "http://{{ provisioner_server_dn }}:8080"
    tectonic_matchbox_rpc_endpoint: "{{ provisioner_server_dn }}:8081"
    tectonic_ingress_domain: "{{ tectonic_ingress_dn }}"
    tectonic_service_cidr: "10.3.0.0/16"
    tectonic_coreos_user: core

  roles:
    - common

  tasks:

  - name: generate custom iSCSI kublet service def
    local_action:
      module: template
      src: templates/coreos-kubelet-service-iscsi.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/coreos-kublet-service
      mode: 0766
    become: false
    run_once: true
    when: tectonic_networking != "canal"

  - name: generate custom iSCSI/Canal kublet service definition
    local_action:
      module: template
      src: templates/coreos-kubelet-service-iscsi-canal.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/coreos-kublet-service
      mode: 0766
    become: false
    run_once: true
    when: tectonic_networking == "canal"

  - name: generate the iSCSI script
    local_action:
      module: template
      src: templates/coreos-iscsi-script.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/coreos-iscsi.sh
      mode: 0766
    run_once: true
    become: false

- hosts: coreos_workers
  become: true
  any_errors_fatal: true
  gather_facts: false
  vars:

  roles:
    - coreos-iscsi-provisioner

