---
- hosts: vmware_db_vms
  remote_user: "{{ remote_user }}"
  gather_facts: false
  tasks:  

  - name: Ensure the local data volume exists
    file:
      path: "/data"
      state: directory
  
  - name: Generate data backup script for data node.
    template:
      src: templates/data-backup.j2
      dest: "/data/data-backup.sh"
      mode: 0711
