---
- hosts: dcos_masters,dcos_agents_private,dcos_agents_public
  remote_user: admin
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
    - name: add internal elastic DNS name to hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^%elastic.idstudios.local'
        line: '192.168.1.80 elastic.idstudios.local'

    - name: daemon-reload 
      shell: systemctl daemon-reload

    - name: start journalctl-filebeat.service
      service:
        name: dcos-journalctl-filebeat.service
        state: restarted
        enabled: yes

    - name: enable filebeat
      service:
        name: filebeat
        state: restarted
        enabled: yes

