---
- hosts: vmware_vms
  remote_user: "admin"
  become: true
  gather_facts: false
  tasks:  

  - name: Get Before Date/Time
    shell: date
    register: before_out

  - name: Stop Chrony
    shell: systemctl stop chronyd

  - name: Sync time manually
    shell: chronyd -q 'server ca.pool.ntp.org iburst'

  - name: Start Chrony
    shell: systemctl start chronyd

  - name: Get After Date/Time
    shell: date
    register: after_out

  - debug: msg="{{ before_out.stdout_lines }} {{ after_out.stdout_lines }} "
