---
- hosts: docker_swarm_worker
  remote_user: root
  tasks:  
  - name: Install tar
    shell: tdnf -y install tar

  - name: Stop the Docker daemon.
    service:
      name: docker
      state: stopped

  - name: Download latest version of docker
    get_url:
      url: https://download.docker.com/linux/static/stable/x86_64/docker-17.06.0-ce.tgz
      dest: ~/docker-17.06.0-ce.tgz
      force: no

  - name: Unpack
    shell: tar --strip-components=1 -C /usr/bin -xzf docker-17.06.0-ce.tgz
    args:
      chdir: ~

  - name: Update Systemd service file
    replace:
      path: /usr/lib/systemd/system/docker.service
      regexp: '^ExecStart=/usr/bin/docker daemon'
      replace: 'ExecStart=/usr/bin/dockerd'

  - name: Systemctl reload
    shell: systemctl daemon-reload

  - name: Enable the Docker daemon as a service and start it.
    service:
      name: docker
      state: started
      enabled: yes  



