
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    drupal_deployment_folder: "{{ inventory_dir | replace(playbook_dir + '/clusters/', '') }}/drupal"
    drupal_deployment_home: "{{ drupal_deployment_folder}}/{{ drupal_stack_name }}"

  roles:
    - common
    - drupal-template
