
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    drupal_deployment_folder: "{{ inventory_dir | replace(playbook_dir + '/clusters/', '') }}/drupal"
    drupal_deployment_home: "{{ drupal_deployment_folder}}/{{ drupal_stack_name }}"

  roles:
    - common

  tasks:

  - name: Determine service port
    set_fact:
      drupal_service_port: 80
    when: drupal_service_port is undefined
    run_once: true

  - debug: var=drupal_service_port
    run_once: true

  - name: Ensure the deployment folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ drupal_deployment_folder }} ]; then mkdir {{ drupal_deployment_folder }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Ensure the deployment home exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ drupal_deployment_home }} ]; then mkdir {{ drupal_deployment_home }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Purge existing yaml 
    local_action:
      module: shell
      _raw_params: "cd {{ drupal_deployment_home }} && rm *.yml"
    become: false
    run_once: true
    ignore_errors: true

  - name: Generate the Drupal manifest
    local_action:
      module: template
      src: templates/drupal/drupal.j2
      dest: "{{ drupal_deployment_home }}/drupal.yml"
      mode: 0755
    run_once: true
    become: false

  - name: Generate the CoreOS Tectonic Ingress manifest
    local_action:
      module: template
      src: templates/drupal/drupal-tectonic-ingress.j2
      dest: "{{ drupal_deployment_home }}/drupal-tectonic-ingress.yml"
      mode: 0755
    run_once: true
    become: false
    when: drupal_nodeport is defined 

  - name: Generate the PKS LB manifest
    local_action:
      module: template
      src: templates/drupal/drupal-pks-lb.j2
      dest: "{{ drupal_deployment_home }}/drupal-pks-lb.yml"
      mode: 0755
    run_once: true
    become: false
    when: drupal_nodeport is undefined

  - name: Generate the Traefik Ingress manifest
    local_action:
      module: template
      src: templates/drupal/drupal-traefik-ingress.j2
      dest: "{{ drupal_deployment_home }}/drupal-traefik-ingress.yml"
      mode: 0755
    run_once: true
    become: false
    when: drupal_nodeport is undefined

  - name: Ensure the loadtests folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ drupal_deployment_home }}/loadtests ]; then mkdir {{ drupal_deployment_home }}/loadtests; fi"
    become: false
    run_once: true
    ignore_errors: true
    
  - name: Generate the medium load tests
    local_action:
      module: template
      src: templates/drupal/tests/drupal-load-test-med.j2
      dest: "{{ drupal_deployment_home }}/loadtests/med_load.yml"
      mode: 0755
    run_once: true
    become: false
    
  - name: Generate the heavy load tests
    local_action:
      module: template
      src: templates/drupal/tests/drupal-load-test-heavy.j2
      dest: "{{ drupal_deployment_home }}/loadtests/heavy_load.yml"
      mode: 0755
    run_once: true
    become: false
    