---
- hosts: vmware_vms
  gather_facts: false
  tasks:  
  - name: Scan the VMS for the VM ID
    local_action:
      module: shell
      _raw_params: ssh {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/getallvms | grep {{ vm_name }} | cut -d" " -f1
    register: vm_id
  
  - debug: msg="{{ vm_id.stdout }}"

  - name: Start the VMs
    local_action:
      module: shell
      _raw_params: ssh {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/power.on {{ vm_id.stdout }} 
    when: vm_id.stdout is defined and vm_action == 'start'

  - name: Stop the VMs
    local_action:
      module: shell
      _raw_params: ssh {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/power.off {{ vm_id.stdout }} 
    when: vm_id.stdout is defined and vm_action == 'stop'

  - name: Suspend the VMs
    local_action:
      module: shell
      _raw_params: ssh {{ esxi_user }}@{{ esxi_host }} vim-cmd vmsvc/power.suspend {{ vm_id.stdout }} 
    when: vm_id.stdout is defined and vm_action == 'suspend'
