---
- hosts: all
  gather_facts: false
  remote_user: root
  vars:
    esxi_user: root
    ova_opts: ""
    ova_template_path: "{{ ova_template }}"
    gen_script_folder: ../tmp/{{ cluster_pkg_folder }}
  
  roles:
  - role: common
      
  tasks:  
  - name: ensure the target folder for generated scripts exists
    local_action:
      module: file
      path: "{{ gen_script_folder }}"
      state: directory

  - name: remove existing creation script
    local_action:
      module: file
      path: "{{ gen_script_folder }}/esxi-create-vms"
      state: absent
    run_once: true

  - name: remove existing static net script
    local_action:
      module: file
      path: "{{ gen_script_folder }}/esxi-set-statics"
      state: absent
    run_once: true

  - name: create ovftool script to deploy cluster-node ova to ESXi.
    local_action:
      module: template
      src: templates/ovftool.j2
      dest: "{{ gen_script_folder }}/esxi-create-vms"
      mode: 0711
    run_once: true
  