---
- hosts: docker_swarm_manager
  remote_user: "{{ remote_user }}"
  roles:
  - role: common
      
  tasks:
  - name: fetch the client certs
    fetch:
      src: /etc/certs/docker/{{ item }}.pem
      dest: ../clusters/{{ cluster_pkg_folder }}/api-certs/{{ inventory_hostname }}/
      flat: yes     
    become: true   
    with_items:
      - ca
      - key    
      - cert                    

  - name: generate the client test script
    local_action:
      module: template
      src: templates/test-{{ cluster_type }}.j2
      dest: ../clusters/{{ cluster_pkg_folder }}/test-cluster
      mode: 0766
    when: "inventory_hostname == groups['docker_swarm_manager'][0]"
    become: false
