---
- hosts: all
  remote_user: "{{ remote_user }}"
  become: true
  tasks:
  - name: Stop the docker daemon
    service:
      name: docker
      state: stopped
      enabled: no  

  - name: Enable SSH Firewalld rule
    shell: firewall-cmd --zone=dmz --add-service=mysql --permanent

  - name: Reload the Firewalld rules
    shell: firewall-cmd --reload

  - name: List the active Firewalld rules
    shell: firewall-cmd --list-all    
    register: firewalld_rules

  - debug: msg="{{ firewalld_rules.stdout_lines }}"

  - name: Restart the docker daemon with the new firewall rules
    service:
      name: docker
      state: started
      enabled: yes  
