- hosts: k8s_workers
  become: true
  remote_user: admin
  any_errors_fatal: true
  gather_facts: false
  vars:

  roles:
    - common

  tasks:
    - name: ensure the iSCSId daemon is running and enabled on the nodes
      shell: systemctl enable iscsid && systemctl start iscsid

    - name: verify status of iSCSId daemon 
      shell: systemctl status iscsid
      register: iscsi_out

    - debug: msg="{{ iscsi_out.stdout_lines }}"