---
# This playbook installs knative on Kubernetes
- hosts: all
  remote_user: "{{ remote_user }}"
  become: true
  gather_facts: no
  any_errors_fatal: true
    
  tasks:
  - name: set k8s_knative_version default 
    set_fact:
      k8s_knative_version: "0.10.0"
    run_once: true
    when: "k8s_knative_version is undefined and 
      (k8s_version is not search('1.12') and k8s_version is not search('1.13'))"

  - name: set k8s_knative_version default 
    set_fact:
      k8s_knative_version: "0.4.0"
    run_once: true
    when: "k8s_knative_version is undefined and k8s_version is search('1.13')"

  - name: set k8s_knative_version default 
    set_fact:
      k8s_knative_version: "0.3.0"
    run_once: true
    when: "k8s_knative_version is undefined and k8s_version is search('1.12')"

  - name: set k8s_istio_version default 
    set_fact:
      k8s_istio_version: "1.1.7"
    run_once: true
    when: k8s_istio_version is undefined and k8s_knative_version == "0.10.0"

  - name: set k8s_istio_version default 
    set_fact:
      k8s_istio_version: "1.0.2"
    run_once: true
    when: k8s_istio_version is undefined 

  - debug: msg="k8s_istio_version {{ k8s_istio_version }}"
    run_once: true
  - debug: msg="k8s_knative_version {{ k8s_knative_version }}"
    run_once: true
  - debug: msg="remote_user {{ remote_user }}"
    run_once: true

- hosts: all
  remote_user: "{{ remote_user }}"
  become: true
  gather_facts: no
  any_errors_fatal: true

  vars:
    kube_config_file: "{{ playbook_dir | replace('/ansible', '') }}/clusters/{{ cluster_pkg_folder }}/kube-config"

  roles:
  - role: common
  - role: k8s-settings
  - role: istio
  - role: knative
