
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    galera_cluster_folder: "{{ inventory_dir | replace(playbook_dir + '/clusters/', '') }}/galera"
    galera_cluster_home: "{{ galera_cluster_folder }}/{{ galera_cluster_name }}"

  roles: 
    - common
    - mariadb-galera-template

  