
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    galera_cluster_folder: "{{ inventory_dir | replace(playbook_dir + '/clusters/', '') }}/galera"
    galera_cluster_home: "{{ galera_cluster_folder }}/{{ galera_cluster_name }}"

  roles: 
    - common

  tasks:

  - set_fact: galera_cluster_backup_incremental_interval="15m"
    when: galera_cluster_backup_incremental_interval is undefined

  - debug: var=cluster_pkg_folder
    run_once: true

  - debug: var=galera_cluster_home
    run_once: true

  - name: ensure the cluster folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_folder }} ]; then mkdir {{ galera_cluster_folder }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: ensure the cluster home exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }} ]; then mkdir {{ galera_cluster_home }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: ensure the cluster 3-node sub-folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }}/3 ]; then mkdir {{ galera_cluster_home }}/3; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: ensure the cluster 5-node sub-folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }}/5 ]; then mkdir {{ galera_cluster_home }}/5; fi"
    become: false
    run_once: true
    ignore_errors: true
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: purge existing yaml from 3-node cluster
    local_action:
      module: shell
      _raw_params: "cd {{ galera_cluster_home }}/3 && rm *.yml"
    become: false
    run_once: true
    ignore_errors: true

  - name: purge existing yaml from 5-node cluster
    local_action:
      module: shell
      _raw_params: "cd {{ galera_cluster_home }}/5 && rm *.yml"
    become: false
    run_once: true
    ignore_errors: true
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 3-Node static iSCSI based galera volumes manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-volumes-static.j2
      dest: "{{ galera_cluster_home }}/3/static-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_cluster_seed_iscsi_targetportal is defined

  - name: generate the 3-Node Dynamic iSCSI Targetd based galera volumes manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-volumes-targetd.j2
      dest: "{{ galera_cluster_home }}/3/targetd-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_iscsi_storage_class is defined 

  - name: generate the 3-Node vSphere Targetd based galera volumes manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-vsphere-volumes.j2
      dest: "{{ galera_cluster_home }}/3/vsphere-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is defined 

  - name: generate the 5-Node iSCSI based galera volumes manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-volumes.j2
      dest: "{{ galera_cluster_home }}/5/static-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 5-Node vSphere based galera volumes manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-vsphere-volumes.j2
      dest: "{{ galera_cluster_home }/5/vsphere-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is defined 

  - name: generate the galera 3-nodes manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-nodes.j2
      dest: "{{ galera_cluster_home }}/3/nodes.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the galera 5-nodes manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-nodes.j2
      dest: "{{ galera_cluster_home }}/5/nodes.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the galera 3-nodes manifest with backup agent
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-nodes-backup.j2
      dest: "{{ galera_cluster_home }}/3/nodes-with-backup.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the galera 5-nodes manifest with backup agent
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-nodes-backup.j2
      dest: "{{ galera_cluster_home }}/5/nodes-with-backup.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 3-nodes galera haproxy manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-haproxy.j2
      dest: "{{ galera_cluster_home }}/3/haproxy.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the 3-nodes galera native LB manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-native-lb.j2
      dest: "{{ galera_cluster_home }}/3/galera-native-lb.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the 5-nodes galera haproxy manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-haproxy.j2
      dest: "{{ galera_cluster_home }}/5/haproxy.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 5-nodes galera native LB manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-native-lb.j2
      dest: "{{ galera_cluster_home }}/5/galera-native-lb.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 3-node galera seed manifest
    local_action:
      module: template
      src: templates/galera/galera-seed.j2
      dest: "{{ galera_cluster_home }}/3/seed.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the 5-node galera seed manifest
    local_action:
      module: template
      src: templates/galera/galera-seed.j2
      dest: "{{ galera_cluster_home }}/5/seed.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: generate the 3-node galera external nodeport manifest
    local_action:
      module: template
      src: templates/galera/galera-external-nodeport.j2
      dest: "{{ galera_cluster_home }}/3/external-nodeport.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is undefined 

  - name: generate the 3-node galera external lb manifest
    local_action:
      module: template
      src: templates/galera/galera-external-lb.j2
      dest: "{{ galera_cluster_home }}/3/external-lb.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is defined 

  - name: generate the 5-node galera external nodeport manifest
    local_action:
      module: template
      src: templates/galera/galera-external-access.j2
      dest: "{{ galera_cluster_home }}/5/external-access.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is undefined'

  - name: generate the 5-node galera external lb manifest
    local_action:
      module: template
      src: templates/galera/galera-external-lb.j2
      dest: "{{ galera_cluster_home }}/5/external-lb.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is defined 

  - name: generate the 3-Node restore to seed job manifest
    local_action:
      module: template
      src: templates/galera/galera-restore-seed-job.j2
      dest: "{{ galera_cluster_home }}/3/restore-seed-job.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the 5-node restore to seed job manifest
    local_action:
      module: template
      src: templates/galera/galera-restore-seed-job.j2
      dest: "{{ galera_cluster_home }}/5/restore-seed-job.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'
    
  - name: generate the 3-Node namespace manifest
    local_action:
      module: template
      src: templates/galera/galera-namespace.j2
      dest: "{{ galera_cluster_home }}/3/namespace.yml"
      mode: 0766
    run_once: true
    become: false

  - name: generate the 5-node namespace manifest
    local_action:
      module: template
      src: templates/galera/galera-namespace.j2
      dest: "{{ galera_cluster_home }}/5/namespace.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'
    
  - name: generate the 3-Node purge volumes job manifest
    local_action:
      module: template
      src: templates/galera/3-node/galera-3-purge-volumes-jobs.j2
      dest: "{{ galera_cluster_home }}/3/purge-volumes-jobs.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is undefined 

  - name: generate the 5-node purge volumes job manifest
    local_action:
      module: template
      src: templates/galera/5-node/galera-5-purge-volumes-jobs.j2
      dest: "{{ galera_cluster_home }}/5/purge-volumes-jobs.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is undefined'
    