---
- hosts: all
  remote_user: root
  vars:
    # Docker swarm network can be define in order to be sure that
    # swarm cluster doesn't overlap with you infrastructure
    # docker_swarm_network: 10.10.8.0/24

    # You can set any interface, that is listened by docker engine.
    # e.g. docker_swarm_interface: "eth1"
    docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
    docker_swarm_port: 2377

  tasks:  
  - name: Remove Swarm worker nodes.
    shell: docker swarm leave --force
    changed_when: False
    when: "'docker_swarm_worker' in group_names"
    tags:
      - skip_ansible_lint # Suppressing the linter

  - name: Remove Swarm manager nodes.
    shell: docker swarm leave --force
    changed_when: False
    when: "'docker_swarm_manager' in group_names"
    tags:
      - skip_ansible_lint # Suppressing the linter

