---
# This playbook creates a photon docker swarm

- hosts: all
  remote_user: root
  any_errors_fatal: true
  vars:
    # Docker swarm network can be define in order to be sure that
    # swarm cluster doesn't overlap with you infrastructure
    # docker_swarm_network: 10.10.8.0/24

    # You can set any interface, that is listened by docker engine.
    # e.g. docker_swarm_interface: "eth1"
    docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
    docker_swarm_port: 2377
  roles:
  - role: photon
  - role: swarm
  
  tasks:
  - name: Generate the client test script
    local_action:
      module: template
      src: templates/test-{{ cluster_type }}.j2
      dest: ../tmp/test-cluster
      mode: 0766
    when: "inventory_hostname == groups['docker_swarm_manager'][0]"
