---
# This playbook creates a rhel7 docker swarm

- hosts: all
  remote_user: admin
  become: true
  any_errors_fatal: true
  vars:
    # Docker swarm network can be define in order to be sure that
    # swarm cluster doesn't overlap with you infrastructure
    # docker_swarm_network: 10.10.8.0/24

    # You can set any interface, that is listened by docker engine.
    # e.g. docker_swarm_interface: "eth1"
    #docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
    #docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    docker_swarm_port: 2377
    docker_tls_port: 2376
    contiv_remote_user: admin

  tasks:

  - name: create temp hosts file.
    become: yes
    shell: cp /etc/hosts /etc/hosts.gen

  - name: add IP address of all hosts to all hosts
    become: yes
    lineinfile:
      dest: /etc/hosts.gen
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
    with_items: "{{ groups['all'] }}"  

  - name: promote hosts file.
    become: yes
    shell: cp /etc/hosts.gen /etc/hosts
