---
- hosts: all

  gather_facts: false
  tasks:  
  - name: add SSH keyscan to known hosts entries 
    local_action:
      module: shell
      _raw_params: ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
