---
# This playbook deploys a CoreOS CentOS7 Targetd server for dynamic iSCSI provisioning

- hosts: all
  remote_user: admin
  become: true
  any_errors_fatal: true
  vars:

  roles:
  - role: common
  - role: centos-dcos
  - role: targetd-server