- hosts: all
  gather_facts: false
  vars:
    fusion_vm_folder: ../virtuals
    ova_template_path: "../{{ ova_template }}"
    gen_script_folder: ../tmp/{{ cluster_name }}
    vmware_dhcpd_base_path: '/Library/Preferences/VMware\ Fusion/'
    vmware_dhcpd_cmd: vmnet-cli

  tasks:  
    - name: Remove 2nd Interface - No data network
      local_action:
        module: lineinfile
        path: "{{ fusion_vm_folder }}/{{ inventory_hostname }}.vmwarevm/{{ inventory_hostname }}.vmx"
        state: absent
        regexp: 'ethernet1'
      when: fusion_data_net is undefined
