---
- hosts: all

  gather_facts: false
  become: true
  tasks:  
    - name: install VMware volume driver plugin on swarm nodes
      shell: docker plugin install --grant-all-permissions --alias vsphere store/vmware/docker-volume-vsphere:latest
