---
- hosts: vmware_vms
  gather_facts: false
  tasks:  
    - name: set server_static_ip_wait_seconds if undefined
      set_fact:
        server_static_ip_wait_seconds: 300
      run_once: true
      when: server_static_ip_wait_seconds is undefined

    - name: waiting {{ server_static_ip_wait_seconds }} seconds for VMs to come online
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay={{ server_static_ip_wait_seconds }} timeout=600
      become: false