---
- hosts: vmware_vms
  gather_facts: false
  tasks:  
    - name: Waiting for VMs to come online
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=180 timeout=600
      become: false