- name: Check whether grub.cfg contains "elevator=director"
  command: grep -Fxq "elevator=director" /usr/share/oem/grub.cfg
  register: checkgrub
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Update the CoreOS grub.cfg with custom boot options
  lineinfile:
    dest: /usr/share/oem/grub.cfg
    regexp: "{{ item.regx }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regx: "set linux_append=", line: 'set linux_append="$linux_append coreos.config.url=oem:///coreos-install.json elevator=director"' }
  when: checkgrub.rc == 0

- name: waiting 180 secs for servers to start up and fetch their permanent ip addresses
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=180 timeout=600
  become: false
  when: checkgrub.rc == 0

