---
- name: generate TLS 
  shell: export SAN=DNS.1:{{ provisioner_server_dn }} && ./cert-gen
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls

- name: create matchbox default cert location
  shell: mkdir -p /etc/matchbox

- name: move certificates to matchbox default location
  shell: cp ca.crt server.crt server.key /etc/matchbox
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls

- name: fetch the matchbox certificates
  fetch:
    src: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls/{{ item }}
    dest: ../clusters/{{ cluster_pkg_folder }}/matchbox-certs/
    flat: yes        
  with_items:
    - ca.crt
    - ca.key
    - server.crt
    - server.key 
    - client.crt
    - client.key 

- name: load systemd Service
  shell: systemctl daemon-reload

- name: start and enable the matchbox daemon
  service:
    name: matchbox
    state: restarted
    enabled: yes  

- name: show matchbox service status
  shell: systemctl status matchbox
  register: matchbox_status

- debug: msg="{{ matchbox_status.stdout_lines }}"

- name: verify Matchbox service
  shell: "curl http://{{ provisioner_server_dn }}:8080"
  register: matchbox_resp

- debug: msg="{{ matchbox_resp.stdout_lines }}"

- name: verify matchbox service gRPC TLS
  shell: "openssl s_client -connect {{ provisioner_server_dn }}:8081 -CAfile /etc/matchbox/ca.crt -cert scripts/tls/client.crt -key scripts/tls/client.key"
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/
  register: matchbox_grpc_resp

- debug: msg="{{ matchbox_grpc_resp.stdout_lines }}"

- name: download user specified CoreOS stable release
  shell: ./scripts/get-coreos stable {{ coreos_stable_version }} .  
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64
  when: coreos_stable_version is defined

- name: download user specified CoreOS beta release
  shell: ./scripts/get-coreos beta {{ coreos_beta_version }} .  
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64
  when: coreos_beta_version is defined

- name: download user specified CoreOS alpha release
  shell: ./scripts/get-coreos alpha {{ coreos_alpha_version }} .  
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64
  when: coreos_alpha_version is defined

- name: promote fetched CoreOS releases
  shell: cp -r coreos /var/lib/matchbox/assets
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64
