---
- name: Generate TLS 
  shell: export SAN=DNS.1:{{ provisioner_server_dn }} && ./cert-gen
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls

- name: Create matchbox default cert location
  shell: mkdir -p /etc/matchbox

- name: Move certificates to matchbox default location
  shell: cp ca.crt server.crt server.key /etc/matchbox
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls

- name: Fetch the matchbox certificates
  fetch:
    src: /home/admin/matchbox-v0.7.0-linux-amd64/scripts/tls/{{ item }}
    dest: ../clusters/{{ cluster_pkg_folder }}/matchbox-certs/
    flat: yes        
  with_items:
    - ca.crt
    - server.crt
    - server.key 

- name: Load Systemd Service
  shell: systemctl daemon-reload

- name: Start and enable the matchbox daemon
  service:
    name: matchbox
    state: restarted
    enabled: yes  

- name: Show Matchbox service status
  shell: systemctl status matchbox
  register: matchbox_status

- debug: msg="{{ matchbox_status.stdout_lines }}"

- name: Verify Matchbox service
  shell: "curl http://{{ provisioner_server_dn }}:8080"
  register: matchbox_resp

- debug: msg="{{ matchbox_resp.stdout_lines }}"

- name: Verify Matchbox service gRPC TLS
  shell: "openssl s_client -connect {{ provisioner_server_dn }}:8081 -CAfile /etc/matchbox/ca.crt -cert scripts/tls/client.crt -key scripts/tls/client.key"
  args:
    chdir: /home/admin/matchbox-v0.7.0-linux-amd64/
  register: matchbox_grpc_resp

- debug: msg="{{ matchbox_grpc_resp.stdout_lines }}"
