- name: verifying CoreOS {{ coreos_linux_channel }} {{ coreos_linux_version }} on the Matchbox server
  stat: path=/var/lib/matchbox/assets/coreos/{{ coreos_linux_version }}
  register: stat_result

- name: fetching CoreOS {{ coreos_linux_channel }} {{ coreos_linux_version }} on the Matchbox server
  shell: "cd matchbox-*-linux-amd64 && ./scripts/get-coreos {{ coreos_linux_channel }} {{ coreos_linux_version }} ."
  args:
    chdir: /home/admin
  register: fetch_output
  become: true
  become_user: root
  when: stat_result.stat.exists == False

- debug: msg="{{ fetch_output.stdout_lines }}" 
  when: stat_result.stat.exists == False

- name: install into the Matchbox assets
  shell: "cd matchbox-*-linux-amd64 && cp -r coreos/{{ coreos_linux_version }} /var/lib/matchbox/assets/coreos/ "
  args:
    chdir: /home/admin
  become: true
  become_user: root
  when: stat_result.stat.exists == False
