- name: Import the Kernel Repo GPG
  shell: "rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"
  when: "update_kernel is defined"

- name: Add the Kernel Repo
  shell: "rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm"
  when: "update_kernel is defined"

- name: Intall the LT Kernel
  shell: "yum --enablerepo=elrepo-kernel install -y kernel-lt"
  when: "update_kernel is defined"

- name: Update Grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^%GRUB_DEFAULT'
    line: 'GRUB_DEFAULT=0'
  when: "update_kernel is defined"

- name: Re-gen Grub
  shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  when: "update_kernel is defined"

- name: Restart machines with new kernels
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  when: "update_kernel is defined"

- name: Waiting 90 secs for VMs to come online
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=90 timeout=600
  become: false
  when: "update_kernel is defined"

- name: Verify Kernel
  shell: "uname -ra"
  register: kernel_out
  when: "update_kernel is defined"
  
- debug: msg="{{ kernel_out.stdout_lines }}"
  when: "update_kernel is defined"
