
- name: label default namespace for Isitio
  shell: "kubectl label namespace default istio-injection=enabled"
  become: true
  ignore_errors: true
  register: label_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ label_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: install Knative 0.4.0 Serving
  shell: |
    kubectl apply --filename https://github.com/knative/serving/releases/download/v0.4.0/serving.yaml 
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: install Knative 0.4.0 Build
  shell: |
    kubectl apply --filename https://github.com/knative/build/releases/download/v0.4.0/build.yaml 
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: install Knative 0.4.0 Eventing
  shell: |
    kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml 
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: install Knative 0.4.0 Eventing Sources
  shell: |
    kubectl apply --filename https://github.com/knative/eventing-sources/releases/download/v0.4.0/release.yaml 
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: install Knative 0.4.0 Monitoring
  shell: |
    kubectl apply --filename https://github.com/knative/serving/releases/download/v0.4.0/monitoring.yaml 
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]
    and k8s_knative_install_monitoring|bool == True

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]
    and k8s_knative_install_monitoring|bool == True

- name: install Knative 0.4.0 Serving ClusterRole
  shell: |
    kubectl apply --filename https://raw.githubusercontent.com/knative/serving/v0.4.0/third_party/config/build/clusterrole.yaml
  become: true
  register: knative_out
  when: inventory_hostname == groups['k8s_masters'][0]

- debug: msg="{{ knative_out.stdout_lines }}"
  when: inventory_hostname == groups['k8s_masters'][0]

- name: give the Knative deployment a few seconds to spin up
  pause:
    seconds: 30
  when: inventory_hostname == groups['k8s_masters'][0]

- name: wait for the Knative deployment to complete
  shell: "kubectl get pods --all-namespaces | grep -E 'Pending|ContainerCreating|PodInitializing' | wc -l  | xargs"
  become: true
  register: pending_pods
  until: "pending_pods.stdout == '0'"
  retries: 100
  delay: 10    
  when: inventory_hostname == groups['k8s_masters'][0]

