  - name: Verify NFS Shares file
    local_action:
      module: stat
      path: "../clusters/{{ cluster_pkg_folder }}/nfs_shares.yml"
    register: nfs_shares_config
    run_once: true
    become: false
  
  - name: Load NFS Shares file
    include_vars:
      file: "../clusters/{{ cluster_pkg_folder }}/nfs_shares.yml"
    run_once: true
    when: nfs_shares_config.stat.exists == True

  - name: load empty nfs_shares
    include_vars:
      file: "nfs-shares-empty.yml"
    run_once: true
    when: nfs_shares_config.stat.exists == False

  - debug: msg="{{ nfs_shares }}"
    when: nfs_shares_config.stat.exists == True
    run_once: true

  - name: ensure the NFS mounts exist
    file:
      path: "{{ item.folder }}"
      state: directory
    when: "item.folder is defined and (item.group is undefined or item.group in group_names)"
    with_items: 
      - "{{ nfs_shares }}"

  - name: create fstab entry for shared storage and backup volumes
    lineinfile:
      path: "/etc/fstab"
      state: present
      regexp: "{{ item.folder }}"
      line: "{{ item.fstab }}"
    when: "item.fstab is defined and (item.group is undefined or item.group in group_names)"
    with_items: 
      - "{{ nfs_shares }}"

  - name: unmount the volumes
    shell: umount {{ item.folder }}
    when: "item.folder is defined and (item.group is undefined or item.group in group_names)"
    ignore_errors: true
    with_items: 
      - "{{ nfs_shares }}"
    
  - name: mount the volumes
    shell: mount {{ item.folder }}
    when: "item.folder is defined and (item.group is undefined or item.group in group_names)"
    with_items: 
      - "{{ nfs_shares }}"

  - name: list the volume
    shell: ls -al "{{ item.folder }}"
    register: local_out
    when: "item.folder is defined and (item.group is undefined or item.group in group_names)"
    with_items: 
      - "{{ nfs_shares }}"
