  - name: Load NFS Shares file
    include_vars:
      file: "../clusters/{{ cluster_name }}/nfs_shares.yml"
    run_once: true

  - debug: msg="{{ nfs_shares }}"
    run_once: true

  - name: Ensure the NFS mounts exist
    file:
      path: "{{ item.folder }}"
      state: directory
    when: "item.group is undefined or item.group in group_names"
    with_items: 
      - "{{ nfs_shares }}"

  - name: Create fstab entry for shared storage and backup volumes
    lineinfile:
      path: "/etc/fstab"
      state: present
      line: "{{ item.fstab }}"
    when: item.group is undefined or "item.group in group_names"
    with_items: 
      - "{{ nfs_shares }}"

  - name: Unmount the volumes
    shell: mount {{ item.folder }}
    when: item.group is undefined or "item.group in group_names"
    ignore_errors: true
    with_items: 
      - "{{ nfs_shares }}"
    
  - name: Mount the volumes
    shell: mount {{ item.folder }}
    when: item.group is undefined or "item.group in group_names"
    with_items: 
      - "{{ nfs_shares }}"

  - name: List the volume
    shell: ls -al "{{ item.folder }}"
    register: local_out
    when: item.group is undefined or "item.group in group_names"
    with_items: 
      - "{{ nfs_shares }}"

  - debug: msg="{{ local_out.stdout_lines }}"
    when: item.group is undefined or "item.group in group_names"
    with_items: 
      - "{{ nfs_shares }}"
